/**
 * Application constants
 */

// GOAL:
// RELATION TO OTHER FILES, file_path, FUNCTIONS, COMPONENTS AND FEATURES:
// Note if any: components to merge with, similar or redundant component, usage patterns, next steps if any

export const API_KEY_ERROR_MESSAGE = 'API key error';

// Memory collection names
export const MEMORY_COLLECTION_NAME = 'orion_memory';

// API endpoints
const getBaseUrl = () => process.env.NEXTAUTH_URL || 'http://localhost:3000';
export const TOMIDES_PROFILE_DATA = '';
export const LLM_API_ENDPOINT = `${getBaseUrl()}/api/orion/llm`;
export const MEMORY_API_ENDPOINT = `${getBaseUrl()}/api/orion/memory`;

// Ask a Question parameters
export const DEFAULT_REQUEST_TYPE = 'general_question';
export const DEFAULT_PRIMARY_CONTEXT = 'user_profile';

export const ASK_QUESTION_REQUEST_TYPE = 'ask_question_request';

export const REQUEST_TYPES = {
  GENERAL_QUESTION: 'general_question',
  IDEA_BRAINSTORM: 'idea_brainstorm',
  OPPORTUNITY_EVALUATION: 'opportunity_evaluation',
  CV_TAILORING: 'cv_tailoring',
  WHATSAPP_CHAT_ANALYSIS: 'whatsapp_chat_analysis',
  OUTREACH_DRAFTING: 'outreach_drafting',
  NARRATIVE_GENERATION: 'narrative_generation',
  ASK_QUESTION_REQUEST: 'ask_question_request',
};

export enum PageNames {
  ADMIN_DASHBOARD = 'Admin Dashboard',
  JOURNAL_AND_REFLECTION = 'Journal & Reflection',
  OPPORTUNITY_PIPELINE = 'Opportunity Pipeline',
  HABITICA_TODO_MANAGEMENT = 'Habitica Todo Management',
  NARRATIVE_CLARITY_STUDIO = 'Narrative Clarity Studio',
  LOCAL_FILE_EXPLORER = 'Local File Explorer',
  MEMORY_MANAGER = 'Memory Manager',
  IDEA_INCUBATOR = 'Idea Incubator',
  WHATSAPP_HELPER = 'WhatsApp Helper',
  INSIGHTS = 'Insights',
  AGENTIC = 'Agentic Workflow',
  DRAFT_COMM = 'Draft Communications',
  NETWORKING = 'Networking',
  // Add other page names as needed
}

export enum SessionStateKeys {
  LAST_ACTIVITY_TIMESTAMP = 'lastActivityTimestamp',
  CURRENT_ACTIVE_FEATURE = 'currentActiveFeature',
  USER_PREFERENCES = 'userPreferences',
  AGW_APPROACH_RADIO = 'agwApproachRadio',
  AGW_GOAL_INPUT = 'agwGoalInput',
  AGW_OUTPUT_TEXT = 'agwOutputText',
  AGW_PRIMARY_MODEL = 'agwPrimaryModel',
  ASK_Q_ANSWER = 'askQAnswer',
  ASK_Q_INPUT = 'askQInput',
  ASK_Q_MODEL_APPROACH = 'askQModelApproach',
  ASK_Q_PRIMARY_MODEL = 'askQPrimaryModel',
  ASK_Q_PROCESSING = 'askQProcessing',
  ATM_NUM_RESULTS = 'atmNumResults',
  ATM_PASTED_TEXT = 'atmPastedText',
  ATM_SEARCH_QUERY = 'atmSearchQuery',
  ATM_SOURCE_ID = 'atmSourceId',
  ATM_TAGS_INPUT = 'atmTagsInput',
  CREWAI_AVAILABLE = 'crewaiAvailable',
  CURRENT_MOOD = 'currentMood',
  DC_COMM_TYPE = 'dcCommType',
  DC_CONTEXT = 'dcContext',
  DC_CONTEXT_OR_TEMPLATE = 'dcContextOrTemplate',
  DC_DRAFT = 'dcDraft',
  DC_DRAFT_OR_OPTIONS = 'dcDraftOrOptions',
  DC_GENERATING = 'dcGenerating',
  DC_MODEL_APPROACH = 'dcModelApproach',
  DC_NUM_OPTIONS = 'dcNumOptions',
  DC_PRIMARY_MODEL = 'dcPrimaryModel',
  DC_RECIPIENTS = 'dcRecipients',
  DC_SAVE_TAGS_INPUT = 'dcSaveTagsInput',
  DC_TOPIC = 'dcTopic',
  DC_USER_CONTEXT = 'dcUserContext',
  ENABLED_STEPS_PIPELINE = 'enabledStepsPipeline',
  HABITICA_API_TOKEN = 'habiticaApiToken',
  HABITICA_USER_ID = 'habiticaUserId',
  JOURNAL_MODEL_APPROACH = 'journalModelApproach',
  JOURNAL_PRIMARY_MODEL = 'journalPrimaryModel',
  JOURNAL_PROCESSING = 'journalProcessing',
  JOURNAL_REFLECTION = 'journalReflection',
  JOURNAL_SHOW_SAVE_FORM = 'journalShowSaveForm',
  JOURNAL_TEXT = 'journalText',
  LLM_CONFIGURED = 'llmConfigured',
  MEMORY_INITIALIZED = 'memoryInitialized',
  MM_BROAD_SEARCH_QUERY = 'mmBroadSearchQuery',
  MM_DETAILED_SEARCH_QUERY = 'mmDetailedSearchQuery',
  MM_EMAIL_DRAFT = 'mmEmailDraft',
  MM_GENERATING_EMAIL = 'mmGeneratingEmail',
  MM_GENERATING_LINKEDIN_MESSAGE = 'mmGeneratingLinkedinMessage',
  MM_LINKEDIN_MESSAGE_DRAFT = 'mmLinkedinMessageDraft',
  MM_OPPORTUNITY_SEARCH_RESULTS = 'mmOpportunitySearchResults',
  MM_OPPORTUNITY_SELECTED_STAKEHOLDERS = 'mmOpportunitySelectedStakeholders',
  MM_OPPORTUNITY_SEARCH_TERM = 'mmOpportunitySearchTerm',
  MM_PROCESSING_OPPORTUNITY_SEARCH = 'mmProcessingOpportunitySearch',
  MM_QDRANT_RESULTS = 'mmQdrantResults',
  MM_SEARCH_MODE = 'mmSearchMode',
  MM_SEMANTIC_SEARCH_ENABLED = 'mmSemanticSearchEnabled',
  MM_SELECTED_OPPORTUNITY_STAKEHOLDERS = 'mmSelectedOpportunityStakeholders',
  MM_SELECTED_OPPORTUNITY_URL = 'mmSelectedOpportunityUrl',
  MM_SEMANTIC_SEARCH_TERM = 'mmSemanticSearchTerm',
  MM_SOURCE_FILTER = 'mmSourceFilter',
  MM_TAG_FILTER = 'mmTagFilter',
  NOTIFICATION_SETTINGS_EMAIL_ENABLED = 'notificationSettingsEmailEnabled',
  NOTIFICATION_SETTINGS_PUSH_ENABLED = 'notificationSettingsPushEnabled',
  OPENAI_API_KEY = 'openaiApiKey',
  OPPORTUNITY_CREATE_PROCESSING = 'opportunityCreateProcessing',
  OPPORTUNITY_CURRENT_ANALYSIS_SUMMARY = 'opportunityCurrentAnalysisSummary',
  OPPORTUNITY_DETAILS_FETCHED = 'opportunityDetailsFetched',
  OPPORTUNITY_EVALUATION_FEEDBACK = 'opportunityEvaluationFeedback',
  OPPORTUNITY_EVALUATION_PROCESSING = 'opportunityEvaluationProcessing',
  OPPORTUNITY_EVALUATION_RESULT = 'opportunityEvaluationResult',
  OPPORTUNITY_EVALUATION_SUGGESTIONS = 'opportunityEvaluationSuggestions',
  OPPORTUNITY_EVAL_SECTION_VISIBLE = 'opportunityEvalSectionVisible',
  OPPORTUNITY_IS_SAVING = 'opportunityIsSaving',
  OPPORTUNITY_LAST_SAVED_AT = 'opportunityLastSavedAt',
  OPPORTUNITY_NOTES = 'opportunityNotes',
  OPPORTUNITY_REASONS_TO_PURSUES = 'opportunityReasonsToPursues',
  OPPORTUNITY_REASONS_TO_SKIP = 'opportunityReasonsToSkip',
  OPPORTUNITY_RISK_REWARD_ANALYSIS = 'opportunityRiskRewardAnalysis',
  OPPORTUNITY_SELECTED_OPPORTUNITY_ID = 'opportunitySelectedid',
  OPPORTUNITY_SHOW_EVALUATION_RESULT = 'opportunityShowEvaluationResult',
  OPPORTUNITY_SHOW_SUMMARY_FEEDBACK = 'opportunityShowSummaryFeedback',
  OPPORTUNITY_TAB_CURRENT_TAB = 'opportunityTabCurrentTab',
  QDRANT_API_KEY = 'qdrantApiKey',
  QW_ANSWER = 'qwAnswer',
  QW_CONTEXT = 'qwContext',
  QW_EMAIL_DRAFT = 'qwEmailDraft',
  QW_GENERATING_EMAIL = 'qwGeneratingEmail',
  QW_GENERATING_LINKEDIN_MESSAGE = 'qwGeneratingLinkedinMessage',
  QW_LINKEDIN_MESSAGE_DRAFT = 'qwLinkedinMessageDraft',
  QW_MODEL_APPROACH = 'qwModelApproach',
  QW_PRIMARY_MODEL = 'qwPrimaryModel',
  QW_PROCESSING = 'qwProcessing',
  QW_QUESTION_INPUT = 'qwQuestionInput',
  QW_SAVE_TAGS_INPUT = 'qwSaveTagsInput',
  SHOW_CBT_FORM = 'showCbtForm',
  SHOW_JOURNAL_ENTRY_FORM = 'showJournalEntryForm',
  SHOW_SAVE_OPTIONS = 'showSaveOptions',
  SHOW_WHATSAPP_DRAFTER = 'showWhatsappDrafter',
  WHATSAPP_DRAFTER_CONTEXT = 'whatsappDrafterContext',
  WHATSAPP_DRAFTER_DRAFT = 'whatsappDrafterDraft',
  WHATSAPP_DRAFTER_GENERATING = 'whatsappDrafterGenerating',
  WHATSAPP_DRAFTER_MODEL_APPROACH = 'whatsappDrafterModelApproach',
  WHATSAPP_DRAFTER_PRIMARY_MODEL = 'whatsappDrafterPrimaryModel',
  WHATSAPP_DRAFTER_RECIPIENT = 'whatsappDrafterRecipient',
  WHATSAPP_DRAFTER_SAVE_TAGS_INPUT = 'whatsappDrafterSaveTagsInput',
  WHATSAPP_DRAFTER_SENTIMENT = 'whatsappDrafterSentiment',
  WHATSAPP_DRAFTER_TONE = 'whatsappDrafterTone',
  WHATSAPP_DRAFTER_TOPIC = 'whatsappDrafterTopic',
  WHATSAPP_DRAFTER_USER_CONTEXT = 'whatsappDrafterUserContext',
  WHATSAPP_DRAFTER_WORD_COUNT = 'whatsappDrafterWordCount',
  WORKFLOW_CURRENT_STEP = 'workflowCurrentStep',
  WORKFLOW_EXECUTION_LOG = 'workflowExecutionLog',
  WORKFLOW_IS_RUNNING = 'workflowIsRunning',
  WORKFLOW_LAST_ERROR = 'workflowLastError',
  WORKFLOW_PROGRESS = 'workflowProgress',
  WORKFLOW_STATUS = 'workflowStatus',
  MM_BROWSE_MODEL = 'mmBrowseModel',
  MM_CRUD_MODEL = 'mmCrudModel',
  MM_OP_RADIO = 'mmOpRadio',
  MM_RAW_INPUT = 'mmRawInput',
  MOOD_NOTE = 'moodNote',
  NARRATIVE_CONTENT = 'narrativeContent',
  NARRATIVE_CONTEXT = 'narrativeContext',
  NARRATIVE_GENERATING = 'narrativeGenerating',
  NARRATIVE_LENGTH = 'narrativeLength',
  NARRATIVE_REQUIREMENTS = 'narrativeRequirements',
  NARRATIVE_TITLE = 'narrativeTitle',
  NARRATIVE_TONE = 'narrativeTone',
  NARRATIVE_TYPE = 'narrativeType',
  NETWORKING_MODEL_APPROACH = 'networkingModelApproach',
  NETWORKING_PRIMARY_MODEL = 'networkingPrimaryModel',
  NETWORKING_QUERY = 'networkingQuery',
  NETWORKING_ROLES = 'networkingRoles',
  OUTREACH_DRAFT = 'outreachDraft',
  OUTREACH_GENERATING = 'outreachGenerating',
  OUTREACH_GOAL = 'outreachGoal',
  OUTREACH_OPPORTUNITY = 'outreachOpportunity',
  OUTREACH_TONE = 'outreachTone',
  OUTREACH_TYPE = 'outreachType',
  PIPELINE_STATE = 'pipelineState',
  PIPELINE_STEP = 'pipelineStep',
  PROCESSED_STAKEHOLDERS_NET = 'processedStakeholdersNet',
  ROUTINES_MORNING_COMPLETED = 'routinesMorningCompleted',
  ROUTINES_EXECUTION_STATUS = 'routinesExecutionStatus',
  ROUTINES_LAST_RUN = 'routinesLastRun',
  ROUTINES_SCRAPED_LINKS = 'routinesScrapedLinks',
  SESSION_STATE_INITIALIZED = 'sessionStateInitialized',
  SI_DESCRIPTION_INPUT = 'siDescriptionInput',
  SI_FEATURE_INPUT = 'siFeatureInput',
  SI_FEEDBACK_TYPE = 'siFeedbackType',
  SI_IMPROVEMENT_SUGGESTIONS = 'siImprovementSuggestions',
  STAKEHOLDERS_LIST_NET = 'stakeholdersListNet',
  TOMIDES_PROFILE_DATA = 'tomidesProfileData',
  USER_NAME = 'userName',
  VOICE_PREFERENCE = 'voicePreference',
  WH_GENERATED_RESPONSE = 'whGeneratedResponse',
  WH_TEMPLATE_INPUT = 'whTemplateInput',
  MODEL_APPROACH_PIPELINE = 'modelApproachPipeline',
  ROUTINES_EVENING_COMPLETED = 'routinesEveningCompleted',
}
