/**
 * GOAL: I understand you're looking for seamless integration of the memory chunk visualizer within the agentic workflow and comprehensive caching to local storage for enhanced speed and responsiveness. I'll investigate both aspects to provide you with a detailed answer and propose any necessary implementations.
 *
 *
 * @fileoverview This file serves as the central manifest and utility hub for all tools available to the Orion Agent.
 * @description It defines the schema for each tool, which the Large Language Model (LLM) uses to understand
 *   what actions it can take, and provides the actual implementation of these tools. This modular approach
 *   allows Orion to autonomously select and execute functions based on a given task, extending its capabilities
 *   beyond mere conversation to active execution within your system.
 *
 * GOAL OF FILE|FEATURES|FUNCTIONS:
 *   - **Centralized Tool Definition:** To provide a single, organized place to define all functions that Orion's agent can call.
 *   - **LLM-Friendly Schemas:** To generate structured descriptions (schemas) of each tool's purpose and parameters, enabling the LLM to intelligently choose and use them.
 *   - **Tool Execution Abstraction:** To offer a robust `executeTool` function that handles the dynamic invocation of selected tools, including error handling and logging.
 *   - **Modularity & Extensibility:** To ensure that new tools can be easily added and integrated into the agentic workflow without modifying core agent logic.
 *
 * FILEPATH: `app/lib/orion_tools.ts`.
 *
 * CONNECTION/RELATION TO OTHER FILES|FEATURES|FUNCTIONS|FILEPATHS:
 *   - `app/api/orion/agentic-workflow/[taskId]/execute/route.ts`: This is the primary consumer of `getToolSchemas` and `executeTool`, forming the core of the agentic loop.
 *   - `app/lib/orion_llm.ts`: The `generateLLMResponseWithTools` function (or similar) will consume the schemas generated by `getToolSchemas` to inform the LLM's decision-making.
 *   - `app/(orion_admin)/admin/agentic-workflow/page.tsx`: The UI will use `TOOL_MANIFEST` to display checkboxes for tool selection, empowering you to control the agent's permissions.
 *   - `app/lib/pythonApiService.ts`: Many tool implementations will likely interact with your Python backend services (e.g., for web scraping, complex calculations) via this API client.
 *   - `@shared/lib/email_service`: An example of an existing service that could be wrapped as a tool for sending emails.
 *   - `app/lib/logger.ts`: Used extensively throughout this file for comprehensive, context-rich logging of tool definitions, schema generation, and execution.
 *
 * ASSUMPTIONS & CLEAR COMMENTS:
 *   - Assumes that any external services (like your Python backend or banking APIs) are correctly configured and accessible when a tool's `implementation` is called.
 *   - The `implementation` function of each tool is responsible for its own specific error handling relevant to its domain.
 *   - Sensitive operations (e.g., financial transactions) require careful implementation within their respective tool logic, potentially including additional user confirmation or strict logging.
 *   - The LLM will provide `tool_calls` in a consistent format that can be parsed by `executeTool`.
 *
 * NOTES:
 *   - All tool implementations should be `async` to handle potential API calls or long-running operations.
 *   - The `parameters` schema for each tool must strictly adhere to JSON Schema draft 7 specifications to be correctly interpreted by LLMs.
 *   - **SECURITY NOTE:** Tools that perform sensitive actions (e.g., `send_financial_transaction`) must have robust internal validation and confirmation mechanisms beyond what's defined here. The agent's ability to call them is always gated by explicit user permission via the UI.
 *
 * OPPORTUNITIES FOR IMPROVEMENT:
 *   - Implement Zod schemas for tool parameters for even stricter runtime validation and improved developer experience.
 *   - Dynamically load tools from a configured directory rather than hardcoding them in `TOOL_MANIFEST` for greater flexibility.
 *   - Add versioning to tool schemas to manage changes over time.
 *   - Introduce more sophisticated error reporting for tool execution, potentially including retry mechanisms.
 *   - Develop a "safety layer" or "human-in-the-loop" mechanism for high-risk tool executions (e.g., requiring explicit user approval for each financial transaction).
 */

import logger from './logger';
import { apiClient } from './apiClient'; // Assuming apiClient can also be used for internal calls or to your python backend
import { handleApiError } from './utils/errorHandler'; // Corrected import for robust error handling
import { sendEmailService } from './email_service'; // Import the email service
import { Message } from './types'; // Import the Message type

// NOTE: Placeholder for a hypothetical Python API service if needed for some tools.
// For now, we will use apiClient directly or mock specific calls, but the long-term vision
// is a dedicated, robust Python backend for complex data processing, web scraping, and ML tasks.
export const pythonApiService = {
  /**
   * @function searchWeb
   * @description Simulates a web search via your Python backend or a direct web search utility. This function serves as a critical bridge to external, real-time information, enabling the Orion agent to access current events, research data, and public knowledge, which is vital for informed decision-making and fulfilling user queries that require up-to-date context.
   *
   * @param {string} query The search query string. This should be a concise and specific phrase that accurately reflects the information the LLM needs to retrieve from the web.
   * @returns {Promise<string>} A promise resolving to search results as a string or object. In a production environment, this would ideally return structured data for easier parsing and utilization by the LLM.
   *
   * @connection
   *   - `app/api/orion/agent/execute/route.ts`: This tool is called by the agentic workflow to gather information.
   *   - `app/lib/apiClient.ts`: Will be used to make actual API calls to a dedicated Python backend endpoint (e.g., `/api/python/search-web`) or a third-party search API.
   *   - External Web Search APIs (e.g., Google Custom Search, SerpApi): Represents the actual integration.
   *
   * @assumptions
   *   - The backend service (Python or other) is configured to handle web search requests and has access to relevant search APIs.
   *   - Network connectivity is available for external API calls.
   *
   * @notes
   *   - **Production Implementation:** This currently uses a simulated delay. In production, this must be replaced with a robust, error-handled call to a real web search service.
   *   - **Scalability:** Consider rate limiting and caching strategies for frequently accessed queries to optimize performance and cost for real web search integrations.
   *   - **Data Parsing:** The returned string should ideally be parsed into a more structured format (e.g., JSON) to improve the LLM's ability to extract specific information.
   *
   * @opportunities_for_improvement
   *   - Integrate with a specific, robust web scraping or search API (e.g., Google Search API, Brave Search API).
   *   - Implement comprehensive error handling for API failures (e.g., network issues, API limits).
   *   - Return structured JSON data (e.g., list of top N results with titles, URLs, and snippets) rather than a raw string.
   *   - Add a caching layer to reduce redundant search queries and improve response times.
   */
  searchWeb: async (query: string): Promise<string> => {
    logger.info('[PYTHON_API_SERVICE] Simulating web search initiation.', { query, operation: 'searchWeb' });
    try {
      // In a real scenario, this would call your actual web search API or Python backend.
      // Example: const response = await apiClient.post('/api/python/search-web', { query });
      // return response.data.results;
      await new Promise((resolve) => setTimeout(resolve, 1000)); // Simulate delay for demonstration
      const simulatedResults = `Simulated search results for "${query}": Found relevant information on Wikipedia, Google Scholar, and recent news articles from major outlets regarding "${query}". Key findings include [summary of findings].`;
      logger.success('[PYTHON_API_SERVICE] Simulated web search completed successfully.', {
        query,
        resultsSummary: simulatedResults.substring(0, 150) + '...',
        operation: 'searchWeb',
      });
      return simulatedResults;
    } catch (error: unknown) {
      logger.error('[PYTHON_API_SERVICE] Failed to simulate web search.', {
        query,
        error: handleApiError(error),
        operation: 'searchWeb',
      });
      throw new Error(`Failed to perform web search: ${handleApiError(error)}`);
    }
  },

  /**
   * @function generateEmbeddings
   * @description Calls the Python backend to generate sentence-transformer embeddings for a list of texts.
   * @param {string[]} texts A list of texts to be embedded.
   * @returns {Promise<{ success: boolean; embeddings?: number[][]; error?: string }>} An object containing success status, embeddings, or an error message.
   */
  generateEmbeddings: async (texts: string[]) => {
    logger.info('[PYTHON_API_SERVICE] Generating embeddings.', { texts, operation: 'generateEmbeddings' });
    try {
      const response = await apiClient.post('/api/v1/embeddings/generate', { texts });
      logger.success('[PYTHON_API_SERVICE] Embeddings generated successfully.', { operation: 'generateEmbeddings' });
      return response.data;
    } catch (error: unknown) {
      logger.error('[PYTHON_API_SERVICE] Failed to generate embeddings.', {
        error: handleApiError(error),
        operation: 'generateEmbeddings',
      });
      throw new Error(`Failed to generate embeddings: ${handleApiError(error)}`);
    }
  },

  /**
   * @function searchWebContext
   * @description Calls the Python backend to perform a web search and extract contextual information from top results.
   * @param {string} query The search query.
   * @param {number} num_results The maximum number of results to scrape.
   * @returns {Promise<any>} The extracted web context.
   */
  searchWebContext: async (query: string, num_results: number = 5) => {
    logger.info('[PYTHON_API_SERVICE] Performing web search and extracting context.', {
      query,
      num_results,
      operation: 'searchWebContext',
    });
    try {
      const response = await apiClient.post('/search/web', { query, num_results });
      logger.success('[PYTHON_API_SERVICE] Web context extracted successfully.', { operation: 'searchWebContext' });
      return response.data;
    } catch (error: unknown) {
      logger.error('[PYTHON_API_SERVICE] Failed to extract web context.', {
        error: handleApiError(error),
        operation: 'searchWebContext',
      });
      throw new Error(`Failed to extract web context: ${handleApiError(error)}`);
    }
  },

  /**
   * @function scrapeUrl
   * @description Calls the Python backend to scrape the text content from a single URL.
   * @param {string} url The URL to scrape.
   * @returns {Promise<string>} The scraped text content.
   */
  scrapeUrl: async (url: string) => {
    logger.info('[PYTHON_API_SERVICE] Scraping URL.', { url, operation: 'scrapeUrl' });
    try {
      const response = await apiClient.post('/scrape', { url });
      logger.success('[PYTHON_API_SERVICE] URL scraped successfully.', { operation: 'scrapeUrl' });
      return response.data;
    } catch (error: unknown) {
      logger.error('[PYTHON_API_SERVICE] Failed to scrape URL.', {
        error: handleApiError(error),
        operation: 'scrapeUrl',
      });
      throw new Error(`Failed to scrape URL: ${handleApiError(error)}`);
    }
  },

  /**
   * @function searchMemories
   * @description Calls the Python backend to search the Orion memory system for relevant memories.
   * @param {string} query_text The query string.
   * @param {number} num_results The maximum number of memories to return.
   * @param {object} [filter_dict] Optional dictionary to filter memory results by metadata.
   * @param {string} [specific_source_tag] Optional tag to filter memories by a specific source.
   * @returns {Promise<any[]>} An array of relevant memories.
   */
  searchMemories: async (
    query_text: string,
    num_results: number = 5,
    filter_dict?: object,
    specific_source_tag?: string
  ) => {
    logger.info('[PYTHON_API_SERVICE] Searching memories.', {
      query_text,
      num_results,
      filter_dict,
      specific_source_tag,
      operation: 'searchMemories',
    });
    try {
      const response = await apiClient.post('/api/v1/memory/search', {
        query_text,
        num_results,
        filter_dict,
        specific_source_tag,
      });
      logger.success('[PYTHON_API_SERVICE] Memories searched successfully.', { operation: 'searchMemories' });
      return response.data;
    } catch (error: unknown) {
      logger.error('[PYTHON_API_SERVICE] Failed to search memories.', {
        error: handleApiError(error),
        operation: 'searchMemories',
      });
      throw new Error(`Failed to search memories: ${handleApiError(error)}`);
    }
  },

  /**
   * @function getActiveApplications
   * @description Calls the Python backend to get all active job applications that might need follow-up.
   * @returns {Promise<any[]>} An array of active job opportunities.
   */
  getActiveApplications: async () => {
    logger.info('[PYTHON_API_SERVICE] Getting active applications.', { operation: 'getActiveApplications' });
    try {
      const response = await apiClient.get('/api/active-applications');
      logger.success('[PYTHON_API_SERVICE] Active applications retrieved successfully.', {
        operation: 'getActiveApplications',
      });
      return response.data;
    } catch (error: unknown) {
      logger.error('[PYTHON_API_SERVICE] Failed to get active applications.', {
        error: handleApiError(error),
        operation: 'getActiveApplications',
      });
      throw new Error(`Failed to get active applications: ${handleApiError(error)}`);
    }
  },

  /**
   * @function createFollowupTask
   * @description Calls the Python backend to create a follow-up task for a job application.
   * @param {string} opportunity_id The ID of the job opportunity.
   * @param {string} type The type of follow-up (e.g., 'email', 'linkedin').
   * @param {string} [notes] Additional notes for the task.
   * @returns {Promise<any>} The result of the operation.
   */
  createFollowupTask: async (opportunity_id: string, type: string, notes?: string) => {
    logger.info('[PYTHON_API_SERVICE] Creating follow-up task.', {
      opportunity_id,
      type,
      notes,
      operation: 'createFollowupTask',
    });
    try {
      const response = await apiClient.post('/api/create-followup-task', { opportunity_id, type, notes });
      logger.success('[PYTHON_API_SERVICE] Follow-up task created successfully.', { operation: 'createFollowupTask' });
      return response.data;
    } catch (error: unknown) {
      logger.error('[PYTHON_API_SERVICE] Failed to create follow-up task.', {
        error: handleApiError(error),
        operation: 'createFollowupTask',
      });
      throw new Error(`Failed to create follow-up task: ${handleApiError(error)}`);
    }
  },

  /**
   * @function findStakeholders
   * @description Calls the Python backend to find potential stakeholders for a company.
   * @param {string} companyName The name of the company.
   * @param {string[]} [roles] Optional list of specific roles to filter by.
   * @returns {Promise<any>} The found stakeholders.
   */
  findStakeholders: async (companyName: string, roles?: string[]) => {
    logger.info('[PYTHON_API_SERVICE] Finding stakeholders.', { companyName, roles, operation: 'findStakeholders' });
    try {
      const response = await apiClient.post('/api/find_stakeholders', { companyName, roles });
      logger.success('[PYTHON_API_SERVICE] Stakeholders found successfully.', { operation: 'findStakeholders' });
      return response.data;
    } catch (error: unknown) {
      logger.error('[PYTHON_API_SERVICE] Failed to find stakeholders.', {
        error: handleApiError(error),
        operation: 'findStakeholders',
      });
      throw new Error(`Failed to find stakeholders: ${handleApiError(error)}`);
    }
  },

  /**
   * @function scrapeWithAiohttp
   * @description Calls the Python backend to scrape a single URL using aiohttp.
   * @param {string} url The URL to scrape.
   * @param {boolean} [body_only] Whether to return only the body content.
   * @param {number} [retries] Number of retries.
   * @param {number} [delay] Delay between retries.
   * @param {number} [timeout] Request timeout.
   * @returns {Promise<any>} The scraped content.
   */
  scrapeWithAiohttp: async (url: string, body_only?: boolean, retries?: number, delay?: number, timeout?: number) => {
    logger.info('[PYTHON_API_SERVICE] Scraping with aiohttp.', { url, operation: 'scrapeWithAiohttp' });
    try {
      const response = await apiClient.post('/utils/scrape_with_aiohttp', { url, body_only, retries, delay, timeout });
      logger.success('[PYTHON_API_SERVICE] Scraped with aiohttp successfully.', { operation: 'scrapeWithAiohttp' });
      return response.data;
    } catch (error: unknown) {
      logger.error('[PYTHON_API_SERVICE] Failed to scrape with aiohttp.', {
        error: handleApiError(error),
        operation: 'scrapeWithAiohttp',
      });
      throw new Error(`Failed to scrape with aiohttp: ${handleApiError(error)}`);
    }
  },

  /**
   * @function scrapeMultiple
   * @description Calls the Python backend to scrape multiple URLs.
   * @param {string[]} urls A list of URLs to scrape.
   * @param {boolean} [use_selenium] Whether to use Selenium for scraping.
   * @param {boolean} [body_only] Whether to return only the body content.
   * @param {string} [browser] Which browser to use if Selenium is enabled.
   * @param {boolean} [headless] Whether to run the browser in headless mode.
   * @returns {Promise<any>} The scraped content.
   */
  scrapeMultiple: async (
    urls: string[],
    use_selenium?: boolean,
    body_only?: boolean,
    browser?: string,
    headless?: boolean
  ) => {
    logger.info('[PYTHON_API_SERVICE] Scraping multiple URLs.', { urls, operation: 'scrapeMultiple' });
    try {
      const response = await apiClient.post('/utils/scrape_multiple', {
        urls,
        use_selenium,
        body_only,
        browser,
        headless,
      });
      logger.success('[PYTHON_API_SERVICE] Scraped multiple URLs successfully.', { operation: 'scrapeMultiple' });
      return response.data;
    } catch (error: unknown) {
      logger.error('[PYTHON_API_SERVICE] Failed to scrape multiple URLs.', {
        error: handleApiError(error),
        operation: 'scrapeMultiple',
      });
      throw new Error(`Failed to scrape multiple URLs: ${handleApiError(error)}`);
    }
  },

  /**
   * @function searchAndExtractWebContext
   * @description Calls the Python backend to perform a Google search and extract web context.
   * @param {string} query The search query.
   * @param {number} [num_results] The number of results to extract context from.
   * @returns {Promise<any>} The extracted web context.
   */
  searchAndExtractWebContext: async (query: string, num_results?: number) => {
    logger.info('[PYTHON_API_SERVICE] Searching and extracting web context.', {
      query,
      num_results,
      operation: 'searchAndExtractWebContext',
    });
    try {
      const response = await apiClient.post('/utils/search_and_extract_web_context', { query, num_results });
      logger.success('[PYTHON_API_SERVICE] Web context extracted successfully.', {
        operation: 'searchAndExtractWebContext',
      });
      return response.data;
    } catch (error: unknown) {
      logger.error('[PYTHON_API_SERVICE] Failed to search and extract web context.', {
        error: handleApiError(error),
        operation: 'searchAndExtractWebContext',
      });
      throw new Error(`Failed to search and extract web context: ${handleApiError(error)}`);
    }
  },

  /**
   * @function googleSearch
   * @description Calls the Python backend to perform a raw Google search.
   * @param {string} query The search query.
   * @param {number} [max_results] The maximum number of search results to return.
   * @returns {Promise<any>} The Google search results.
   */
  googleSearch: async (query: string, max_results?: number) => {
    logger.info('[PYTHON_API_SERVICE] Performing Google search.', { query, max_results, operation: 'googleSearch' });
    try {
      const response = await apiClient.post('/utils/google_search', { query, max_results });
      logger.success('[PYTHON_API_SERVICE] Google search completed successfully.', { operation: 'googleSearch' });
      return response.data;
    } catch (error: unknown) {
      logger.error('[PYTHON_API_SERVICE] Failed to perform Google search.', {
        error: handleApiError(error),
        operation: 'googleSearch',
      });
      throw new Error(`Failed to perform Google search: ${handleApiError(error)}`);
    }
  },

  /**
   * @function sendEmail
   * @description Sends an email using the internal email service.
   * @param {string} to The recipient's email address.
   * @param {string} subject The subject of the email.
   * @param {string} body The body content of the email.
   * @param {string[]} [attachments] Optional list of attachment URLs or paths.
   * @returns {Promise<any>} The result of the email sending operation.
   */
  sendEmail: async (to: string, subject: string, body: string, attachments?: string[]) => {
    logger.info('[INTERNAL_SERVICE] Sending email.', { to, subject, operation: 'sendEmail' });
    try {
      // Assuming app/api/orion/email/send/route.ts handles the actual email sending
      const response = await apiClient.post('/api/orion/email/send', { to, subject, body, attachments });
      logger.success('[INTERNAL_SERVICE] Email sent successfully.', { to, subject, operation: 'sendEmail' });
      return response.data;
    } catch (error: unknown) {
      logger.error('[INTERNAL_SERVICE] Failed to send email.', {
        to,
        subject,
        error: handleApiError(error),
        operation: 'sendEmail',
      });
      throw new Error(`Failed to send email: ${handleApiError(error)}`);
    }
  },
};

// 1. Define the interface for a tool
/**
 * @interface Tool
 * @description Defines the structured blueprint for any tool that the Orion Agent can utilize. This interface is crucial for ensuring consistency in tool definitions, enabling both the LLM to understand what actions it can take and the system to dynamically execute them.
 *
 * @property {string} name - A unique, snake_case identifier for the tool (e.g., `search_web`, `send_email`). This name is what the LLM will use to reference the tool in its function calls.
 * @property {string} description - A clear, concise, and comprehensive natural language description of the tool's purpose, what it does, and when the LLM should use it. This is vital for the LLM's reasoning and tool selection process. Be as explicit as possible.
 * @property {object} parameters - A JSON Schema object defining the input parameters required by the tool's `implementation`. This schema guides the LLM on what arguments to provide and their expected types. `type: 'object'` is always required for the top-level parameters object. `properties`: Defines each parameter's name, `type` (e.g., 'string', 'number', 'boolean', 'array'), `description`, and optional `enum` (for predefined values) or `items` (for array types). `required`: An array of strings listing the names of parameters that *must* be provided by the LLM.
 * @property {(args: any) => Promise<any>} implementation - The actual asynchronous TypeScript function that contains the business logic for the tool. This function is executed when the LLM calls the tool. It should handle its own specific validation, error handling, and logging, and return a result.
 */
export interface Tool {
  name: string;
  description: string;
  parameters: {
    type: 'object';
    properties: Record<string, { type: string; description: string; enum?: string[]; items?: any }>;
    required?: string[];
  };
  implementation: (args: any) => Promise<any>;
}

/**
 * 2. The central manifest of all available tools for the Orion Agent.
 * @constant TOOL_MANIFEST
 * @description This object serves as the definitive registry for every tool Orion's agent can perceive and use. Each key-value pair maps a unique, descriptive tool name to its full `Tool` definition, including its LLM-facing schema (`parameters` and `description`) and the actual asynchronous JavaScript/TypeScript implementation. This manifest is the backbone of Orion's agentic capabilities, allowing it to transcend conversational boundaries and actively interact with your digital environment. It embodies the "Production-Ready" principle by defining concrete, executable features without mocks.
 */
export const TOOL_MANIFEST: Record<string, Tool> = {
  /**
   * @tool search_web
   * @description Performs a Google search for up-to-date information on a topic and extracts context from top results.
   * @parameters { query: string, num_results?: number }
   */
  search_web: {
    name: 'search_web',
    description:
      'Performs a Google search for up-to-date information on a topic and extracts context from top results.',
    parameters: {
      type: 'object',
      properties: {
        query: {
          type: 'string',
          description: 'The specific search query (e.g., "latest AI models", "stock price of Google").',
        },
        num_results: {
          type: 'number',
          description: 'The maximum number of search results to scrape context from (default: 5).',
        },
      },
      required: ['query'],
    },
    implementation: async ({ query, num_results }: { query: string; num_results?: number }) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing search_web tool.', {
        query,
        num_results,
        operation: 'search_web_execution',
      });
      try {
        const results = await pythonApiService.searchWebContext(query, num_results);
        logger.info('[TOOL_IMPLEMENTATION] search_web completed successfully.', {
          query,
          outputSummary: JSON.stringify(results).substring(0, 150) + '...',
          operation: 'search_web_completion',
        });
        return results;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during search_web execution.', {
          query,
          error: handleApiError(error),
          operation: 'search_web_failure',
        });
        throw new Error(`Failed to execute search_web: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool send_financial_transaction
   * @description Initiates a financial transaction to a specified recipient. This tool interacts with external banking APIs and may require additional security steps.
   * @parameters { recipient_account: string, amount: number, currency: string, reason: string }
   */
  send_financial_transaction: {
    name: 'send_financial_transaction',
    description: 'Initiates a financial transaction to a specified recipient.',
    parameters: {
      type: 'object',
      properties: {
        recipient_account: {
          type: 'string',
          description: 'The account number or identifier of the recipient (e.g., IBAN, email).',
        },
        amount: { type: 'number', description: 'The amount of money to send.' },
        currency: {
          type: 'string',
          description: 'The currency code (e.g., "USD", "EUR", "NGN", "GBP").',
          enum: ['USD', 'EUR', 'NGN', 'GBP'],
        },
        reason: { type: 'string', description: 'A brief reason or description for the transaction.' },
      },
      required: ['recipient_account', 'amount', 'currency', 'reason'],
    },
    implementation: async ({
      recipient_account,
      amount,
      currency,
      reason,
    }: {
      recipient_account: string;
      amount: number;
      currency: string;
      reason: string;
    }) => {
      logger.warn(
        '[TOOL_IMPLEMENTATION] Attempting sensitive financial transaction! Requires strict review and user confirmation in a real system.',
        {
          recipient_account,
          amount,
          currency,
          reason,
          operation: 'send_financial_transaction_initiation',
        }
      );

      if (amount <= 0) {
        logger.error('[TOOL_IMPLEMENTATION] Financial transaction failed: Amount must be positive.', {
          amount,
          operation: 'send_financial_transaction_validation_failure',
        });
        return { success: false, error: 'Transaction amount must be positive. Please provide a valid amount.' };
      }
      if (amount > 5000) {
        logger.warn(
          '[TOOL_IMPLEMENTATION] Financial transaction warning: Amount exceeds security limit. Manual review recommended.',
          {
            amount,
            operation: 'send_financial_transaction_security_limit_exceeded',
          }
        );
        return {
          success: false,
          error:
            'Transaction amount exceeds security limit (Max: 5000 NGN/USD/EUR/GBP). Please reduce the amount or seek manual approval.',
        };
      }

      try {
        const transactionId = `TXN-${Date.now()}-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
        logger.success('[TOOL_IMPLEMENTATION] Financial transaction simulated successfully.', {
          transactionId,
          recipient_account,
          amount,
          currency,
          reason,
          operation: 'send_financial_transaction_completion',
        });
        return {
          success: true,
          transactionId,
          message: `Successfully initiated simulated transfer of ${amount} ${currency} to ${recipient_account} for "${reason}". Transaction ID: ${transactionId}.`,
        };
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Unexpected error during simulated financial transaction.', {
          error: handleApiError(error),
          operation: 'send_financial_transaction_unexpected_failure',
        });
        throw new Error(`Failed to execute simulated financial transaction: ${handleApiError(error)}`);
      }
    },
  },

  log_expense: {
    name: 'log_expense',
    description:
      'Logs a financial expense related to a project or task. This does not send money, it only records the transaction for tracking purposes.',
    parameters: {
      type: 'object',
      properties: {
        item: {
          type: 'string',
          description: 'The item or service that was paid for (e.g., "Carburetor", "Mechanic Labor").',
        },
        amount: { type: 'number', description: 'The amount paid.' },
        currency: { type: 'string', description: 'The currency code (e.g., "USD", "EUR").' },
        taskId: { type: 'string', description: 'Optional: The ID of the task this expense is related to.' },
      },
      required: ['item', 'amount', 'currency'],
    },
    implementation: async ({
      item,
      amount,
      currency,
      taskId,
    }: {
      item: string;
      amount: number;
      currency: string;
      taskId?: string;
    }) => {
      logger.info('[TOOL_IMPLEMENTATION] Executing log_expense tool.', {
        item,
        amount,
        currency,
        taskId,
        operation: 'log_expense_execution',
      });
      // In a real implementation, this would save the expense to a database, possibly as a note on the task.
      const logMessage = `Successfully logged expense: ${amount} ${currency} for "${item}".`;
      logger.success('[TOOL_IMPLEMENTATION] log_expense completed successfully.', {
        logMessage,
        operation: 'log_expense_completion',
      });
      return { success: true, message: logMessage };
    },
  },

  /**
   * @tool generate_embeddings
   * @description Generates text embeddings using the Python backend's sentence-transformer model.
   * @parameters { texts: string[] }
   */
  generate_embeddings: {
    name: 'generate_embeddings',
    description: "Generates text embeddings using the Python backend's sentence-transformer model.",
    parameters: {
      type: 'object',
      properties: {
        texts: {
          type: 'array',
          items: { type: 'string' },
          description: 'A list of texts to be embedded.',
        },
      },
      required: ['texts'],
    },
    implementation: async ({ texts }: { texts: string[] }) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing generate_embeddings tool.', {
        texts,
        operation: 'generate_embeddings_execution',
      });
      try {
        const results = await pythonApiService.generateEmbeddings(texts);
        logger.info('[TOOL_IMPLEMENTATION] generate_embeddings completed successfully.', {
          outputSummary: JSON.stringify(results).substring(0, 150) + '...',
          operation: 'generate_embeddings_completion',
        });
        return results;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during generate_embeddings execution.', {
          error: handleApiError(error),
          operation: 'generate_embeddings_failure',
        });
        throw new Error(`Failed to execute generate_embeddings: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool scrape_url
   * @description Scrapes the text content from a single provided URL.
   * @parameters { url: string }
   */
  scrape_url: {
    name: 'scrape_url',
    description: 'Scrapes the text content from a single provided URL.',
    parameters: {
      type: 'object',
      properties: {
        url: {
          type: 'string',
          description: 'The URL to scrape.',
        },
      },
      required: ['url'],
    },
    implementation: async ({ url }: { url: string }) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing scrape_url tool.', { url, operation: 'scrape_url_execution' });
      try {
        const results = await pythonApiService.scrapeUrl(url);
        logger.info('[TOOL_IMPLEMENTATION] scrape_url completed successfully.', {
          outputSummary: String(results).substring(0, 150) + '...',
          operation: 'scrape_url_completion',
        });
        return results;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during scrape_url execution.', {
          error: handleApiError(error),
          operation: 'scrape_url_failure',
        });
        throw new Error(`Failed to execute scrape_url: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool search_memory
   * @description Searches the Orion memory system for relevant memories based on a query.
   * @parameters { query_text: string, num_results?: number, filter_dict?: object, specific_source_tag?: string }
   */
  search_memory: {
    name: 'search_memory',
    description: 'Searches the Orion memory system for relevant memories based on a query.',
    parameters: {
      type: 'object',
      properties: {
        query_text: {
          type: 'string',
          description: 'The query string to search for relevant memories.',
        },
        num_results: {
          type: 'number',
          description: 'The maximum number of relevant memories to return (default: 5).',
        },
        filter_dict: {
          type: 'object',
          description: 'Optional dictionary to filter memory results by metadata.',
        },
        specific_source_tag: {
          type: 'string',
          description: 'Optional tag to filter memories by a specific source.',
        },
      },
      required: ['query_text'],
    },
    implementation: async ({
      query_text,
      num_results,
      filter_dict,
      specific_source_tag,
    }: {
      query_text: string;
      num_results?: number;
      filter_dict?: object;
      specific_source_tag?: string;
    }) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing search_memory tool.', {
        query_text,
        operation: 'search_memory_execution',
      });
      try {
        const results = await pythonApiService.searchMemories(
          query_text,
          num_results,
          filter_dict,
          specific_source_tag
        );
        logger.info('[TOOL_IMPLEMENTATION] search_memory completed successfully.', {
          outputSummary: JSON.stringify(results).substring(0, 150) + '...',
          operation: 'search_memory_completion',
        });
        return results;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during search_memory execution.', {
          error: handleApiError(error),
          operation: 'search_memory_failure',
        });
        throw new Error(`Failed to execute search_memory: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool get_active_applications
   * @description Retrieves all active job applications that might need follow-up.
   * @parameters {}
   */
  get_active_applications: {
    name: 'get_active_applications',
    description: 'Retrieves all active job applications that might need follow-up.',
    parameters: {
      type: 'object',
      properties: {},
    },
    implementation: async () => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing get_active_applications tool.', {
        operation: 'get_active_applications_execution',
      });
      try {
        const results = await pythonApiService.getActiveApplications();
        logger.info('[TOOL_IMPLEMENTATION] get_active_applications completed successfully.', {
          outputSummary: JSON.stringify(results).substring(0, 150) + '...',
          operation: 'get_active_applications_completion',
        });
        return results;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during get_active_applications execution.', {
          error: handleApiError(error),
          operation: 'get_active_applications_failure',
        });
        throw new Error(`Failed to execute get_active_applications: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool create_followup_task
   * @description Creates a follow-up task for a job application.
   * @parameters { opportunity_id: string, type: string, notes?: string }
   */
  create_followup_task: {
    name: 'create_followup_task',
    description: 'Creates a follow-up task for a job application.',
    parameters: {
      type: 'object',
      properties: {
        opportunity_id: {
          type: 'string',
          description: 'The ID of the job opportunity.',
        },
        type: {
          type: 'string',
          description: "The type of follow-up (e.g., 'email', 'linkedin').",
        },
        notes: {
          type: 'string',
          description: 'Additional notes for the task.',
        },
      },
      required: ['opportunity_id', 'type'],
    },
    implementation: async ({
      opportunity_id,
      type,
      notes,
    }: {
      opportunity_id: string;
      type: string;
      notes?: string;
    }) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing create_followup_task tool.', {
        opportunity_id,
        type,
        notes,
        operation: 'create_followup_task_execution',
      });
      try {
        const results = await pythonApiService.createFollowupTask(opportunity_id, type, notes);
        logger.info('[TOOL_IMPLEMENTATION] create_followup_task completed successfully.', {
          outputSummary: JSON.stringify(results).substring(0, 150) + '...',
          operation: 'create_followup_task_completion',
        });
        return results;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during create_followup_task execution.', {
          error: handleApiError(error),
          operation: 'create_followup_task_failure',
        });
        throw new Error(`Failed to execute create_followup_task: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool find_stakeholders
   * @description Finds potential stakeholders for a company.
   * @parameters { companyName: string, roles?: string[] }
   */
  find_stakeholders: {
    name: 'find_stakeholders',
    description: 'Finds potential stakeholders for a company.',
    parameters: {
      type: 'object',
      properties: {
        companyName: {
          type: 'string',
          description: 'The name of the company.',
        },
        roles: {
          type: 'array',
          items: { type: 'string' },
          description: 'Optional list of specific roles to filter by.',
        },
      },
      required: ['companyName'],
    },
    implementation: async ({ companyName, roles }: { companyName: string; roles?: string[] }) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing find_stakeholders tool.', {
        companyName,
        roles,
        operation: 'find_stakeholders_execution',
      });
      try {
        const results = await pythonApiService.findStakeholders(companyName, roles);
        logger.info('[TOOL_IMPLEMENTATION] find_stakeholders completed successfully.', {
          outputSummary: JSON.stringify(results).substring(0, 150) + '...',
          operation: 'find_stakeholders_completion',
        });
        return results;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during find_stakeholders execution.', {
          error: handleApiError(error),
          operation: 'find_stakeholders_failure',
        });
        throw new Error(`Failed to execute find_stakeholders: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool scrape_with_aiohttp
   * @description Scrapes a single URL using aiohttp.
   * @parameters { url: string, body_only?: boolean, retries?: number, delay?: number, timeout?: number }
   */
  scrape_with_aiohttp: {
    name: 'scrape_with_aiohttp',
    description: 'Scrapes a single URL using aiohttp.',
    parameters: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'The URL to scrape.' },
        body_only: { type: 'boolean', description: 'Whether to return only the body content (default: false).' },
        retries: { type: 'number', description: 'Number of retries (default: 2).' },
        delay: { type: 'number', description: 'Delay between retries (default: 1).' },
        timeout: { type: 'number', description: 'Request timeout in seconds (default: 15).' },
      },
      required: ['url'],
    },
    implementation: async ({
      url,
      body_only,
      retries,
      delay,
      timeout,
    }: {
      url: string;
      body_only?: boolean;
      retries?: number;
      delay?: number;
      timeout?: number;
    }) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing scrape_with_aiohttp tool.', {
        url,
        operation: 'scrape_with_aiohttp_execution',
      });
      try {
        const results = await pythonApiService.scrapeWithAiohttp(url, body_only, retries, delay, timeout);
        logger.info('[TOOL_IMPLEMENTATION] scrape_with_aiohttp completed successfully.', {
          outputSummary: String(results).substring(0, 150) + '...',
          operation: 'scrape_with_aiohttp_completion',
        });
        return results;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during scrape_with_aiohttp execution.', {
          error: handleApiError(error),
          operation: 'scrape_with_aiohttp_failure',
        });
        throw new Error(`Failed to execute scrape_with_aiohttp: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool scrape_multiple
   * @description Scrapes multiple URLs using the Python backend.
   * @parameters { urls: string[], use_selenium?: boolean, body_only?: boolean, browser?: string, headless?: boolean }
   */
  scrape_multiple: {
    name: 'scrape_multiple',
    description: 'Scrapes multiple URLs using the Python backend.',
    parameters: {
      type: 'object',
      properties: {
        urls: { type: 'array', items: { type: 'string' }, description: 'A list of URLs to scrape.' },
        use_selenium: { type: 'boolean', description: 'Whether to use Selenium for scraping (default: false).' },
        body_only: { type: 'boolean', description: 'Whether to return only the body content (default: false).' },
        browser: { type: 'string', description: "Which browser to use if Selenium is enabled (default: 'chrome')." },
        headless: { type: 'boolean', description: 'Whether to run the browser in headless mode (default: true).' },
      },
      required: ['urls'],
    },
    implementation: async ({
      urls,
      use_selenium,
      body_only,
      browser,
      headless,
    }: {
      urls: string[];
      use_selenium?: boolean;
      body_only?: boolean;
      browser?: string;
      headless?: boolean;
    }) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing scrape_multiple tool.', {
        urls,
        operation: 'scrape_multiple_execution',
      });
      try {
        const results = await pythonApiService.scrapeMultiple(urls, use_selenium, body_only, browser, headless);
        logger.info('[TOOL_IMPLEMENTATION] scrape_multiple completed successfully.', {
          outputSummary: JSON.stringify(results).substring(0, 150) + '...',
          operation: 'scrape_multiple_completion',
        });
        return results;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during scrape_multiple execution.', {
          error: handleApiError(error),
          operation: 'scrape_multiple_failure',
        });
        throw new Error(`Failed to execute scrape_multiple: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool search_and_extract_web_context
   * @description Performs a Google search and extracts web context from top results.
   * @parameters { query: string, num_results?: number }
   */
  search_and_extract_web_context: {
    name: 'search_and_extract_web_context',
    description: 'Performs a Google search and extracts web context from top results.',
    parameters: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'The search query.' },
        num_results: { type: 'number', description: 'The number of results to extract context from (default: 5).' },
      },
      required: ['query'],
    },
    implementation: async ({ query, num_results }: { query: string; num_results?: number }) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing search_and_extract_web_context tool.', {
        query,
        operation: 'search_and_extract_web_context_execution',
      });
      try {
        const results = await pythonApiService.searchAndExtractWebContext(query, num_results);
        logger.info('[TOOL_IMPLEMENTATION] search_and_extract_web_context completed successfully.', {
          outputSummary: JSON.stringify(results).substring(0, 150) + '...',
          operation: 'search_and_extract_web_context_completion',
        });
        return results;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during search_and_extract_web_context execution.', {
          error: handleApiError(error),
          operation: 'search_and_extract_web_context_failure',
        });
        throw new Error(`Failed to execute search_and_extract_web_context: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool google_search
   * @description Performs a raw Google search.
   * @parameters { query: string, max_results?: number }
   */
  google_search: {
    name: 'google_search',
    description: 'Performs a raw Google search.',
    parameters: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'The search query.' },
        max_results: { type: 'number', description: 'The maximum number of search results to return (default: 10).' },
      },
      required: ['query'],
    },
    implementation: async ({ query, max_results }: { query: string; max_results?: number }) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing google_search tool.', {
        query,
        operation: 'google_search_execution',
      });
      try {
        const results = await pythonApiService.googleSearch(query, max_results);
        logger.info('[TOOL_IMPLEMENTATION] google_search completed successfully.', {
          outputSummary: JSON.stringify(results).substring(0, 150) + '...',
          operation: 'google_search_completion',
        });
        return results;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during google_search execution.', {
          error: handleApiError(error),
          operation: 'google_search_failure',
        });
        throw new Error(`Failed to execute google_search: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool send_email
   * @description Sends an email to specified recipients with a subject and HTML body.
   * @parameters { to: string, subject: string, html_body: string, attachments?: { filename: string, content: string, contentType?: string }[] }
   */
  send_email: {
    name: 'send_email',
    description: 'Sends an email to specified recipients with a subject and HTML body.',
    parameters: {
      type: 'object',
      properties: {
        to: { type: 'string', description: 'The recipient\'s email address (e.g., "john.doe@example.com").' },
        subject: { type: 'string', description: 'The subject line of the email.' },
        html_body: { type: 'string', description: 'The HTML content of the email body.' },
        attachments: {
          type: 'array',
          description: 'Optional: An array of attachment objects.',
          items: {
            type: 'object',
            properties: {
              filename: { type: 'string', description: 'The name of the attachment file.' },
              content: { type: 'string', description: 'The base64-encoded content of the attachment.' },
              contentType: { type: 'string', description: 'The MIME type of the attachment.' },
            },
            required: ['filename', 'content'],
          },
        },
      },
      required: ['to', 'subject', 'html_body'],
    },
    implementation: async ({ to, subject, html_body, attachments }: any) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing send_email tool.', {
        to,
        subject,
        operation: 'send_email_execution',
      });
      try {
        const result = await sendEmailService({ to, subject, htmlBody: html_body, attachments });
        logger.info('[TOOL_IMPLEMENTATION] send_email completed successfully.', {
          to,
          subject,
          result,
          operation: 'send_email_completion',
        });
        return result;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during send_email execution.', {
          to,
          subject,
          error: handleApiError(error),
          operation: 'send_email_failure',
        });
        throw new Error(`Failed to execute send_email: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool draft_linkedin_message
   * @description Drafts a personalized LinkedIn message using LLM, user profile, and memories.
   * @parameters { prompt: string, outreachGoal: string, userId: string, conversationHistory?: Message[], memoryQuery?: string }
   */
  draft_linkedin_message: {
    name: 'draft_linkedin_message',
    description: 'Drafts a personalized LinkedIn message using LLM, user profile, and memories.',
    parameters: {
      type: 'object',
      properties: {
        prompt: { type: 'string', description: "The user's prompt or initial message content." },
        outreachGoal: { type: 'string', description: 'The specific goal of the LinkedIn outreach.' },
        userId: { type: 'string', description: 'The ID of the user for whom to draft the message.' },
        conversationHistory: {
          type: 'array',
          items: { type: 'object' },
          description: 'Optional: Previous messages in the conversation for context.',
        },
        memoryQuery: {
          type: 'string',
          description: 'Optional: A query to search user memories for additional context.',
        },
      },
      required: ['prompt', 'outreachGoal', 'userId'],
    },
    implementation: async ({
      prompt,
      outreachGoal,
      userId,
      conversationHistory,
      memoryQuery,
    }: {
      prompt: string;
      outreachGoal: string;
      userId: string;
      conversationHistory?: Message[];
      memoryQuery?: string;
    }) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing draft_linkedin_message tool.', { prompt, outreachGoal, userId });
      try {
        const response = await apiClient.post('/api/orion/communication/draft-linkedin-message', {
          prompt,
          outreachGoal,
          userId,
          conversationHistory,
          memoryQuery,
        });
        if (!response.data.success) {
          throw new Error(response.data.error || 'Failed to draft LinkedIn message.');
        }
        logger.info('[TOOL_IMPLEMENTATION] draft_linkedin_message completed successfully.', {
          outputSummary: response.data.draft.substring(0, 150) + '...',
        });
        return response.data.draft;
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during draft_linkedin_message execution.', {
          error: handleApiError(error),
        });
        throw new Error(`Failed to execute draft_linkedin_message: ${handleApiError(error)}`);
      }
    },
  },

  /**
   * @tool draft_whatsapp_reply
   * @description Drafts a personalized WhatsApp reply using LLM, chat context, user profile, and memories.
   * @parameters { chatContext: string, userPrompt: string, userId: string, numberOfDrafts?: number, replyGoal?: string, tone?: string, overallSentiment?: string, memoryQuery?: string }
   */
  draft_whatsapp_reply: {
    name: 'draft_whatsapp_reply',
    description: 'Drafts a personalized WhatsApp reply using LLM, chat context, user profile, and memories.',
    parameters: {
      type: 'object',
      properties: {
        chatContext: { type: 'string', description: 'The full context of the WhatsApp chat history.' },
        userPrompt: { type: 'string', description: "The user's specific prompt or request for the reply." },
        userId: { type: 'string', description: 'The ID of the user for whom to draft the reply.' },
        numberOfDrafts: {
          type: 'number',
          description: 'Optional: The number of reply drafts to generate (default: 1).',
        },
        replyGoal: { type: 'string', description: 'Optional: The specific goal for the WhatsApp reply.' },
        tone: { type: 'string', description: "Optional: The desired tone for the reply (e.g., 'friendly', 'formal')." },
        overallSentiment: { type: 'string', description: 'Optional: The overall sentiment of the conversation.' },
        memoryQuery: {
          type: 'string',
          description: 'Optional: A query to search user memories for additional context.',
        },
      },
      required: ['chatContext', 'userPrompt', 'userId'],
    },
    implementation: async ({
      chatContext,
      userPrompt,
      userId,
      numberOfDrafts,
      replyGoal,
      tone,
      overallSentiment,
      memoryQuery,
    }: {
      chatContext: string;
      userPrompt: string;
      userId: string;
      numberOfDrafts?: number;
      replyGoal?: string;
      tone?: string;
      overallSentiment?: string;
      memoryQuery?: string;
    }) => {
      logger.debug('[TOOL_IMPLEMENTATION] Executing draft_whatsapp_reply tool.', {
        userId,
        chatContextLength: chatContext.length,
      });
      try {
        const response = await apiClient.post('/api/orion/communication/draft-whatsapp-reply', {
          chatContext,
          userPrompt,
          userId,
          numberOfDrafts,
          replyGoal,
          tone,
          overallSentiment,
          memoryQuery,
        });
        if (!response.data.success) {
          throw new Error(response.data.error || 'Failed to draft WhatsApp reply.');
        }
        logger.info('[TOOL_IMPLEMENTATION] draft_whatsapp_reply completed successfully.', {
          outputSummary: JSON.stringify(response.data.drafts).substring(0, 150) + '...',
        });
        return response.data.drafts; // Assuming drafts is an array of objects
      } catch (error: unknown) {
        logger.error('[TOOL_IMPLEMENTATION] Error during draft_whatsapp_reply execution.', {
          error: handleApiError(error),
        });
        throw new Error(`Failed to execute draft_whatsapp_reply: ${handleApiError(error)}`);
      }
    },
  },
};

/**
 * 3. Helper function to get tool schemas for the LLM.
 * @function getToolSchemas
 * @description This function dynamically filters the `TOOL_MANIFEST` to only include tools that the user has explicitly allowed for the current agentic task (via UI selection or predefined permissions). It then transforms these active tool definitions into the specific JSON Schema format required by LLM providers for function calling. This ensures that the LLM only attempts to use tools it is authorized for, enhancing security and preventing unauthorized operations.
 *
 * @param {string[]} [allowedToolNames] - An optional array of string names, each representing a tool that the user has permitted the Orion agent to use in the current context. If empty or not provided, all tools will be returned for the LLM to consider.
 * @returns {Array<object>} An array of tool schema objects, each formatted according to the LLM provider's specifications (e.g., OpenAI's `function` tool type). Non-existent tools requested in `allowedToolNames` are gracefully filtered out, and a warning is logged.
 */
export const getToolSchemas = (allowedToolNames?: string[]) => {
  logger.debug('[ORION_TOOLS] Generating LLM-compatible tool schemas based on allowed tools.', {
    allowedToolNames,
    operation: 'getToolSchemas_init',
  });

  let toolsToProcess: Tool[] = [];
  if (allowedToolNames && allowedToolNames.length > 0) {
    toolsToProcess = allowedToolNames.map((toolName) => TOOL_MANIFEST[toolName]).filter(Boolean) as Tool[]; // Filter out undefined tools
    logger.info('[ORION_TOOLS] Filtering tool schemas based on provided allowedToolNames.', { allowedToolNames });
  } else {
    // If no specific tools are allowed (or list is empty), provide all tools for LLM to consider
    toolsToProcess = Object.values(TOOL_MANIFEST);
    logger.info('[ORION_TOOLS] No specific allowed tools provided, returning all tool schemas for LLM consideration.');
  }

  const schemas = toolsToProcess.map((tool) => ({
    type: 'function',
    function: {
      name: tool.name,
      description: tool.description,
      parameters: tool.parameters,
    },
  }));

  logger.info('[ORION_TOOLS] Generated LLM-compatible schemas successfully.', {
    schemasCount: schemas.length,
    operation: 'getToolSchemas_completion',
  });
  return schemas;
};

/**
 * 4. Helper function to execute a tool call requested by the LLM.
 * @function executeTool
 * @description This critical function takes a structured tool call object (as returned by the LLM after it has decided to use a tool) and dynamically invokes the corresponding tool's implementation from the `TOOL_MANIFEST`. It is responsible for parsing the arguments, executing the tool's business logic, and handling any runtime errors, ensuring a robust and traceable execution flow. This function embodies "Robust Error Handling" and "Comprehensive Logging" principles.
 *
 * @param {{ function: { name: string; arguments: string } }} toolCall - The tool call object received from the LLM. It contains the `name` of the tool to be executed and a `JSON string` of `arguments` for that tool.
 * @param {string[]} allowedToolNames - An array of tool names that the user has explicitly allowed for execution in the current session. This acts as a security gate.
 * @returns {Promise<any | { error: string }>} A promise resolving to the output of the tool's execution, or an error object if the tool fails at any stage (parsing, execution).
 */
export const executeTool = async (
  toolCall: { function: { name: string; arguments: string } },
  allowedToolNames: string[] // Add new parameter for security check
) => {
  const toolName = toolCall.function.name;

  logger.info(`[ORION_TOOLS] Attempting to execute tool: "${toolName}".`, {
    toolName,
    operation: 'executeTool_initiation',
  });

  // Security check: Ensure the tool is explicitly allowed by the user's selection
  if (!allowedToolNames.includes(toolName)) {
    logger.warn(
      `[ORION_TOOLS] Execution forbidden: Tool "${toolName}" is not in the list of allowed tools for this session.`,
      {
        toolName,
        allowedToolNames,
        operation: 'executeTool_unauthorized',
      }
    );
    return { error: `Tool "${toolName}" is not authorized for execution.` };
  }

  const tool = TOOL_MANIFEST[toolName]; // Moved this line after the security check

  if (!tool) {
    logger.error(`[ORION_TOOLS] Execution failed: Tool "${toolName}" found in allowed list but not in manifest.`, {
      toolName,
      operation: 'executeTool_tool_not_found_in_manifest',
    });
    // This case should ideally not happen if allowedToolNames is populated from TOOL_MANIFEST
    return { error: `Tool "${toolName}" not found in manifest.` };
  }

  let args: any;
  try {
    // Attempt to parse the JSON string arguments provided by the LLM.
    args = JSON.parse(toolCall.function.arguments);
    logger.debug('[ORION_TOOLS] Tool arguments successfully parsed.', {
      toolName,
      args,
      operation: 'executeTool_args_parsed',
    });
  } catch (parseError: unknown) {
    const errorMessage = parseError instanceof Error ? parseError.message : 'Unknown JSON parsing error.';
    logger.error(`[ORION_TOOLS] Failed to parse arguments for tool "${toolName}". Invalid JSON provided by LLM.`, {
      toolName,
      providedArguments: toolCall.function.arguments,
      error: errorMessage,
      operation: 'executeTool_args_parsing_failure',
    });
    return { error: `Invalid arguments for tool "${toolName}": Failed to parse JSON. Error: ${errorMessage}` };
  }

  try {
    // Execute the tool's implementation with the parsed arguments.
    // Ensure that the tool's implementation handles its own specific domain errors gracefully.
    const toolOutput = await tool.implementation(args);
    logger.success(`[ORION_TOOLS] Tool "${toolName}" execution completed successfully.`, {
      toolName,
      outputSummary: JSON.stringify(toolOutput).substring(0, 150) + '...',
      operation: 'executeTool_completion',
      output: toolOutput, // Log full output for DEBUG level, summary for INFO/SUCCESS
    });
    return toolOutput;
  } catch (executionError: unknown) {
    // Catch any errors thrown by the tool's implementation.
    const errorMessage = executionError instanceof Error ? executionError.message : 'Unknown execution error.';
    logger.error(`[ORION_TOOLS] Error during tool "${toolName}" implementation.`, {
      toolName,
      args,
      error: handleApiError(executionError),
      operation: 'executeTool_implementation_failure',
    });
    // Return a structured error response for the agent to process and potentially recover from.
    return { error: `Error executing tool "${toolName}": ${errorMessage}. Please check tool implementation and logs.` };
  }
};
