/**
 * @fileoverview This component is responsible for handling the client-side uploading of WhatsApp chat export files
 *   and initiating the backend analysis process. It leverages `react-dropzone` for an intuitive drag-and-drop interface.
 * @description It serves as the initial, crucial step in Orion's WhatsApp chat analysis and reply drafting workflow,
 *   allowing users to securely import their personal chat data. The component manages the UI state during file
 *   selection, upload, and backend processing, providing clear feedback to the user.
 *
 * GOAL OF FILE|FEATURES|FUNCTIONS:
 *   - To provide a robust and user-friendly interface for selecting and initiating the upload of WhatsApp chat transcripts (only .txt files).
 *   - To trigger the backend process (via `/api/orion/whatsapp/analyze`) for parsing and analyzing the uploaded chat data.
 *   - To manage and display real-time feedback to the user regarding the upload status (loading, success, error).
 *   - To ensure secure and private handling of personal conversation data during the client-side upload phase.
 *   - To pass the parsed and analyzed chat data back to the parent component (`DraftCommunicationClientWrapper`) for further display and reply drafting.
 *
 * FILEPATH: `app/components/orion/whatsapp/WhatsAppChatUploader.tsx`.
 *
 * CONNECTION/RELATION TO OTHER FILES|FEATURES|FUNCTIONS|FILEPATHS:
 *   - `app/(orion_admin)/admin/draft-communication/DraftCommunicationClientWrapper.tsx` (parent): Renders this component and receives the `analysisData` via the `onTranscriptUploaded` callback.
 *   - `app/components/orion/whatsapp/WhatsAppChatAnalysis.tsx`: Receives the `analysisData` (parsed by the backend) from the `DraftCommunicationClientWrapper` and displays detailed insights from it.
 *   - `app/components/ui/orion/whatsapp/WhatsAppReplyDrafter.tsx`: Also receives `analysisData` from the `DraftCommunicationClientWrapper` to pre-fill the chat transcript input and inform LLM-based reply suggestions.
 *   - `/api/orion/whatsapp/analyze/route.ts` (backend API): This component makes a `POST` request to this API endpoint, sending the raw chat transcript for processing.
 *   - `http://localhost:8000/analyze-chat` (External Python API Endpoint): This is the *actual* backend service that performs the core parsing and structured analysis of the WhatsApp chat export files, with the results then proxied via the Next.js API route (`/api/orion/whatsapp/analyze`).
 *   - `react-dropzone`: Used for providing the drag-and-drop file upload functionality, enhancing user experience.
 *   - `@/lib/logger.ts`: Utilized for comprehensive, context-rich logging of file operations, API calls, and error events for traceability and debugging.
 *
 * ASSUMPTIONS & CLEAR COMMENTS:
 *   - This component is client-side (`'use client'`) due to its interactive UI and use of browser APIs like `FileReader` and `fetch`.
 *   - Assumes the `/api/orion/whatsapp/analyze` backend API endpoint is operational and correctly configured to receive chat transcripts and return structured analysis data.
 *   - Assumes WhatsApp chat export files are consistently in `.txt` format as generated by WhatsApp's export feature.
 *   - Data privacy is handled by processing chat transcripts locally on the server (via temporary files) and not storing them persistently without explicit user action.
 *
 * NOTES:
 *   - This component is the critical entry point for integrating personal WhatsApp communication data into Orion's advanced analytical and generative capabilities.
 *   - Robust error handling and clear user feedback are paramount due to the sensitive nature of file uploads and external API calls.
 *   - The seamless integration with `react-dropzone` provides an intuitive and efficient file selection process.
 *
 * OPPORTUNITIES FOR IMPROVEMENT:
 *   - **File Size Validation**: Implement more explicit client-side validation for maximum file size to prevent large file uploads from overwhelming the backend or user's browser.
 *   - **Progress Bar for Large Files**: For very large chat files, implement a detailed progress bar (beyond simple loading spinner) to indicate upload and processing progress.
 *   - **Backend Progress Feedback**: Explore mechanisms (e.g., WebSockets, server-sent events) to receive more granular progress updates from the backend during chat analysis, enhancing user experience for long-running operations.
 *   - **Internationalization (i18n)**: Prepare text strings for translation to support users in different languages, as WhatsApp chat exports can vary by locale.
 *   - **Drag-and-Drop Visual Cues**: Enhance visual feedback (e.g., border color changes, text updates) when a file is actively being dragged over the dropzone area.
 *   - **Accessibility Enhancements**: Ensure full accessibility (keyboard navigation, screen reader support) for all interactive elements.
 *   - **Test Coverage**: Increase unit and integration test coverage for file handling, API calls, and state management logic.
 */
'use client';

import React, { useCallback, useState } from 'react';
import { useDropzone } from 'react-dropzone';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Loader2, UploadCloud, CheckCircle, XCircle } from 'lucide-react';
import { toast } from 'react-hot-toast';
import logger from '@/lib/logger';

interface WhatsAppChatUploaderProps {
  onTranscriptUploaded: (data: any) => void; // Expecting parsed data back
}

const WhatsAppChatUploader: React.FC<WhatsAppChatUploaderProps> = ({ onTranscriptUploaded }) => {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  const [fileName, setFileName] = useState<string | null>(null);

  const onDrop = useCallback(
    async (acceptedFiles: File[]) => {
      logger.info('Operation: onDrop | Status: Initiated | Message: File drop detected.');
      if (acceptedFiles.length === 0) {
        setError('Please upload a .txt file.');
        logger.warn('Operation: onDrop | Status: Validation Failed | Message: No files accepted or invalid file type.');
        return;
      }

      const file = acceptedFiles[0];
      if (file.type !== 'text/plain') {
        setError('Only .txt files are supported.');
        logger.warn(
          `Operation: onDrop | Status: Validation Failed | File: ${file.name} | Type: ${file.type} | Message: Invalid file type.`
        );
        return;
      }

      setFileName(file.name);
      setLoading(true);
      setError(null);
      setSuccess(null);

      const reader = new FileReader();
      reader.onload = async (event) => {
        logger.info(
          `Operation: FileReader.onload | Status: Initiated | File: ${file.name} | Message: File reader loaded.`
        );
        try {
          const chatTranscript = event.target?.result as string;

          if (!chatTranscript) {
            setError('Could not read file content.');
            logger.error(
              `Operation: FileReader.onload | Status: Failed | File: ${file.name} | Message: File content is empty or unreadable.`
            );
            setLoading(false);
            return;
          }

          logger.info(
            `Operation: API Call | Status: Initiated | Endpoint: /api/orion/whatsapp/analyze | File: ${file.name} | Message: Sending chat transcript to backend.`
          );
          const response = await fetch('/api/orion/whatsapp/analyze', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({ chatTranscript }),
          });

          if (!response.ok) {
            const errorData = await response.json();
            throw new Error(errorData.error || 'Failed to analyze chat.');
          }

          const analysisResult = await response.json();
          onTranscriptUploaded(analysisResult);
          setSuccess('Chat transcript uploaded and analyzed successfully!');
          logger.success(
            `Operation: API Call | Status: Success | Endpoint: /api/orion/whatsapp/analyze | File: ${file.name} | Message: Chat analysis successful.`
          );
        } catch (err: any) {
          setError(err.message || 'An unknown error occurred during analysis.');
          logger.error(
            `Operation: API Call | Status: Failed | Endpoint: /api/orion/whatsapp/analyze | File: ${file.name} | Error: ${err.message} | Message: Error during chat analysis API call.`
          );
        } finally {
          setLoading(false);
        }
      };

      reader.onerror = (errorEvent) => {
        setError('Error reading file.');
        logger.error(
          `Operation: FileReader.onerror | Status: Failed | File: ${file.name} | Error: ${errorEvent.target?.error} | Message: Error occurred during file read.`
        );
        setLoading(false);
      };

      reader.readAsText(file);
    },
    [onTranscriptUploaded]
  );

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: { 'text/plain': ['.txt'] },
    multiple: false,
  });

  return (
    <div className="space-y-4">
      <Label htmlFor="whatsapp-chat-upload" className="text-sm text-gray-300 block">
        Upload WhatsApp Chat Export (.txt)
      </Label>
      <div
        {...getRootProps()}
        className={`flex flex-col items-center justify-center p-6 border-2 border-dashed rounded-md cursor-pointer transition-colors ${isDragActive ? 'border-blue-500 bg-gray-700' : 'border-gray-600 bg-gray-800'}`}
      >
        <Input {...getInputProps()} id="whatsapp-chat-upload" className="hidden" />
        <UploadCloud className="h-8 w-8 text-gray-400 mb-2" />
        {isDragActive ? (
          <p className="text-blue-300">Drop the chat file here ...</p>
        ) : (
          <p className="text-gray-300">Drag &apos;n&apos; drop a .txt file here, or click to select file</p>
        )}
        <p className="text-xs text-gray-500 mt-1">Only .txt WhatsApp chat export files are supported.</p>
      </div>

      {fileName && <p className="text-sm text-gray-400 mt-2">Selected file: {fileName}</p>}

      {loading && (
        <div className="flex items-center text-blue-400">
          <Loader2 className="mr-2 h-4 w-4 animate-spin" />
          Processing chat for analysis...
        </div>
      )}

      {error && (
        <div className="bg-red-900/30 text-red-300 p-3 rounded-md flex items-center space-x-2">
          <XCircle className="h-5 w-5" />
          <span>Error: {error}</span>
        </div>
      )}

      {success && (
        <div className="bg-green-900/30 text-green-300 p-3 rounded-md flex items-center space-x-2">
          <CheckCircle className="h-5 w-5" />
          <span>{success}</span>
        </div>
      )}
    </div>
  );
};

export default WhatsAppChatUploader;
