/**
 * @fileoverview This API route is the core backend endpoint for generating hyper-personalized WhatsApp reply drafts.
 * @description It orchestrates the process of fetching relevant context from Orion's memory, combining it with user-provided
 *   information (like chat transcript and specific goals), and the user's comprehensive profile. It then leverages
 *   Orion's Large Language Model (LLM) to produce multiple, strategically ranked reply options that align with Tomide's
 *   authentic persona and communication goals. This route is critical for enabling strategic, empathetic,
 *   and emotionally intelligent communication.
 *
 * GOAL OF FILE|FEATURES|FUNCTIONS:
 *   - To receive a robust request for WhatsApp reply drafts, encompassing the message to reply to, chat history, topic/goal,
 *     relationship context, user profile context, and additional instructions.
 *   - To intelligently consult Orion's Qdrant memory for relevant past interactions, knowledge snippets, and communication patterns
 *     that can inform the reply generation, acting as an "Orient" phase input for the LLM.
 *   - To dynamically construct a rich, multi-contextual prompt for the LLM. This prompt precisely defines Tomide's persona (friendly, enthusiastic, approachable,
 *     conversational, informal, appropriate emoji usage, thoughtful humor, emotional nuance), relationship-specific tone adjustments,
 *     and explicit reply goals (e.g., clarify, set boundary, express gratitude, request support, withdraw).
 *   - To interact seamlessly with Orion's LLM services (via `generateLLMResponse`) to generate multiple (defaulting to 3) distinct reply drafts.
 *   - To robustly parse, rank, and return the generated drafts, each accompanied by a one-sentence explanation of its strategy or tone,
 *     and any relevant memories retrieved, enhancing transparency and user decision-making.
 *   - To implement comprehensive error handling and logging at each stage for meticulous traceability and rapid debugging.
 *   - To ensure secure authentication and authorization (`auth`) for every request, safeguarding sensitive personal data.
 *
 * FILEPATH: `app/api/orion/communication/draft-whatsapp-reply/route.ts`.
 *
 * CONNECTION/RELATION TO OTHER FILES|FEATURES|FUNCTIONS|FILEPATHS:
 *   - `app/(orion_admin)/admin/draft-communication/DraftCommunicationClientWrapper.tsx`: The client-side wrapper that orchestrates the overall Draft Communication UI and initiates requests to this API endpoint.
 *   - `app/components/ui/orion/whatsapp/WhatsAppReplyDrafter.tsx`: The primary frontend UI component that collects user input (chat, goals, context) and displays the drafts generated by this API route. It relies on the structured JSON output of this route.
 *   - `generateLLMResponse` (`@/lib/orion_llm`): The fundamental utility function for interacting with various Large Language Model providers (e.g., Groq, Azure, Gemini, OpenRouter), abstracting away LLM-specific complexities.
 *   - `/api/orion/memory/search`: An internal API endpoint invoked by this route to retrieve relevant memory chunks from the Qdrant vector database, enhancing the LLM's contextual understanding.
 *   - `ORION_MEMORY_COLLECTION_NAME` (`@/lib/orion_config`): Defines the specific Qdrant collection used for memory searches, ensuring data is retrieved from the correct knowledge base.
 *   - `auth` (`@/auth`): The NextAuth.js authentication mechanism used to secure this API route, verifying the user's session and protecting sensitive operations.
 *   - `logger` (`@/lib/logger`): Provides comprehensive, context-rich, and level-based logging for every significant operation and error within this route, crucial for monitoring, auditing, and debugging.
 *   - User Profile Context (received in request body): Derived from `useUserProfile` on the frontend and explicitly passed to this backend route for deeper, personalized draft generation.
 *
 * ASSUMPTIONS & CLEAR COMMENTS:
 *   - Assumes that the underlying LLM services (accessed via `generateLLMResponse`) are correctly configured, operational, and capable of generating nuanced, multi-turn conversational replies based on complex prompts.
 *   - Assumes Qdrant (our memory vector database) is running and accessible for efficient and relevant memory searches.
 *   - The `userProfileContext` field, though optional, is highly impactful for personalization; its absence will result in less tailored drafts.
 *   - Robust fallback mechanisms for LLM providers are expected to be handled by the `generateLLMResponse` utility itself, ensuring resilience against external service failures.
 *   - Input validation (currently basic checks) should be comprehensive to prevent unexpected behavior and improve API reliability.
 *   - This route processes sensitive chat data; temporary handling and non-persistent storage are critical unless explicitly saved by user action.
 *   - The LLM's ability to produce specific JSON output format is crucial for frontend parsing; robust error handling for parsing failures is implemented.
 *
 * NOTES:
 *   - This API endpoint is a critical part of Orion's ability to offer sophisticated, strategic communication assistance, moving beyond simple chatbots to intelligent co-creation.
 *   - The deep integration of user profile, real-time conversation context, and historical memory ensures truly personalized, effective, and ethically aligned outputs.
 *   - Security (via authentication) and extensive, context-rich logging are paramount due to the sensitive nature of generating personal communication.
 *   - This route embodies the "Decide" and "Act" phases of the OODA loop by processing observed data and orienting it with memory to then generate and present actionable communication choices.
 *   - The `systemPrompt` and `userObjectivePrompt` are meticulously crafted to guide the LLM's persona, tone, and output format; continuous refinement of these prompts is an ongoing opportunity.
 *
 * OPPORTUNITIES FOR IMPROVEMENT:
 *   - **Advanced Memory Integration**: Implement more sophisticated query mechanisms for `api/orion/memory/search` (e.g., multi-vector queries, time-based filtering) to retrieve even more contextually precise memories.
 *   - **Dynamic LLM Parameters**: (Implemented) The API now gracefully accepts `numberOfDrafts` from the frontend, controlling the quantity of generated replies.
 *   - **Standardized API Error Responses**: Implement a universal error handling middleware or utility to ensure consistent and developer-friendly error response formats across all Orion backend APIs.
 *   - **Comprehensive Usage Tracking & Analytics**: Add detailed metrics for API usage, LLM token consumption, response times, and success rates for performance monitoring, cost analysis, and system optimization.
 *   - **Robust Input Validation (Zod)**: Implement full Zod schema validation for the request body, providing detailed and specific error messages for invalid inputs at the earliest point.
 *   - **Asynchronous LLM Calls & Streaming**: Explore asynchronous processing for LLM calls or streaming responses to the frontend to improve perceived performance and user experience for longer generation times.
 *   - **Pre-analysis of Chat**: (Implemented) The API now receives `overallSentiment` from chat analysis and integrates it into the LLM prompt for emotionally intelligent reply generation.
 *   - **Psychological Principle Prompting**: Introduce specific parameters or instructions to the LLM prompt to subtly or explicitly integrate psychological principles (e.g., Reciprocity, Liking, Scarcity) into reply generation.
 *   - **A/B Testing LLM Prompts**: Implement infrastructure to A/B test different LLM system and user prompts to iteratively optimize reply quality and adherence to persona/goals.
 *   - **Context Window Management**: Develop smarter logic for managing the LLM's context window, especially for very long chat histories, ensuring critical information is retained without exceeding limits.
 *   - **Reply Goal and Tone Integration**: (Implemented) The API now accepts `replyGoal` and `tone` parameters from the frontend and incorporates them into the LLM prompt for tailored reply generation.
 */
import { NextRequest, NextResponse } from 'next/server';

import { generateLLMResponse } from '@/lib/orion_llm';
import { ORION_MEMORY_COLLECTION_NAME } from '@/lib/orion_config';
import { auth } from '@/auth';
import logger from '@/lib/logger';

// Define the type inline:
type DraftCommunicationRequestBody = {
  messageToReplyTo: string;
  messageHistory?: string;
  topicOrGoal: string;
  relationshipContext: string;
  userProfileContext?: string;
  additionalInstructions?: string;
  numberOfDrafts?: number;
  replyGoal?: string; // New: Specific goal for the reply (e.g., clarify, set_boundary)
  tone?: string; // New: Desired tone for the reply (e.g., empathetic, assertive)
  overallSentiment?: string; // New: Overall sentiment of the chat (e.g., positive, neutral, negative)
};

// Define a minimal type for ScoredMemoryPoint inline
// (only the payload.text field is used)
type ScoredMemoryPoint = {
  payload: { text: string };
};

export async function POST(request: NextRequest) {
  const startTime = Date.now();
  logger.info(`[API /draft-whatsapp-reply] Received request`, { timestamp: new Date().toISOString() });
  const session = await auth();
  if (!session || !session.user) {
    logger.error(`[API /draft-whatsapp-reply] Unauthorized access attempt.`);
    return NextResponse.json({ success: false, error: 'Unauthorized' }, { status: 401 });
  }

  try {
    const body: DraftCommunicationRequestBody = await request.json();
    logger.info(`[API /draft-whatsapp-reply] Request body received`, {
      topicOrGoal: body.topicOrGoal,
      relationshipContext: body.relationshipContext,
      replyGoal: body.replyGoal, // Log new field
      tone: body.tone, // Log new field
      overallSentiment: body.overallSentiment, // Log new field
    });

    const {
      messageToReplyTo,
      messageHistory,
      topicOrGoal,
      relationshipContext,
      userProfileContext,
      additionalInstructions,
      numberOfDrafts = 3,
      replyGoal,
      tone,
      overallSentiment, // Destructure new field
    } = body;

    if (!messageToReplyTo || !topicOrGoal) {
      logger.error('[API /draft-whatsapp-reply] Validation failed: Missing messageToReplyTo or topicOrGoal.');
      return NextResponse.json(
        {
          success: false,
          error: 'Message to reply to and your reply goal are required.',
        },
        { status: 400 }
      );
    }

    // --- Workflow Step 1: Consult Memory (Qdrant) ---
    logger.info('[API /draft-whatsapp-reply] Consulting memory for similar contexts...');
    let relevantMemories: string[] = [];
    try {
      const internalApiUrlBase = process.env.NEXTAUTH_URL || 'http://localhost:3000';
      const memorySearchResponse = await fetch(`${internalApiUrlBase}/api/orion/memory/search`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          queryText: `Context for replying to a WhatsApp message about: ${topicOrGoal}\n\nMessage: ${messageToReplyTo}`,
          limit: 5,
          collectionName: ORION_MEMORY_COLLECTION_NAME,
          filter: {
            must: [
              {
                key: 'payload.type',
                match: {
                  any: ['whatsapp_reply_sample', 'journal_entry', 'general_note'],
                },
              },
            ],
          },
        }),
      });

      const memoryData = await memorySearchResponse.json();
      if (memoryData.success && memoryData.results && memoryData.results.length > 0) {
        relevantMemories = memoryData.results.map((point: ScoredMemoryPoint) => point.payload.text);
        logger.info(`[API /draft-whatsapp-reply] Found ${relevantMemories.length} relevant memories.`);
      } else {
        logger.info('[API /draft-whatsapp-reply] No relevant memories found.');
      }
    } catch (memError: unknown) {
      logger.warn('[API /draft-whatsapp-reply] Could not consult memory, proceeding without it.', {
        error: memError instanceof Error ? memError.message : String(memError),
        stack: memError instanceof Error ? memError.stack : 'No stack trace available',
      });
    }

    // --- Workflow Step 2: Construct Rich LLM Prompt ---
    logger.info('[API /draft-whatsapp-reply] Constructing rich LLM prompt...');
    // The detailed instructions for the LLM on how to behave as you.
    const systemPrompt = `You are Tomide Adeoye. Your task is to draft replies for WhatsApp as if you are him.\n        Your general persona: Friendly, enthusiastic, intelligent, ambitious, dedicated, and caring. You use conversational, informal language with contractions. Your tone is generally simple, avoiding buzzwords. Use emojis sparingly and appropriately. When humor is used, it should be thoughtful.\n        Your core life goals involve achieving financial freedom and a top-tier career via a postgraduate degree and relocation. Your values are Freedom, Logic, Growth, Stability, and Creation.\n\n        Adapt your tone based on the specified relationship context:\n        - timi_girlfriend: The recipient is Timi, your girlfriend. The tone MUST be warm, loving, deeply affectionate, and reflect your lib history. Use terms of endearment naturally.\n        - close_friend: The recipient is a close friend. Maintain a casual, warm, and personal tone, using humor where appropriate.\n        - family_member: The recipient is a family member. The tone should be respectful, caring, and supportive.\n        - professional_colleague or new_professional_contact: Maintain a warm yet professional tone. Ensure clarity and respect.\n        - formal_correspondence: Adopt a more formal and authoritative tone.\n        - default: Use a generally friendly and approachable tone.\n\n        ${tone ? `**Desired Tone for this Reply:** ${tone}. Ensure the tone is consistent throughout the draft.` : ''}\n\n        ${overallSentiment ? `**Overall Sentiment of the Chat:** The chat expresses a predominant ${overallSentiment} sentiment. Tailor your reply to acknowledge and respond appropriately to this emotional tone.` : ''}\n\n        Analyze the provided context, memory snippets, and instructions to generate high-quality, authentic replies.\n\n        User's full profile context for deeper personality understanding:\n        ${userProfileContext}\n        `;

    const userObjectivePrompt = `\n        **Task:** Generate ${numberOfDrafts} distinct reply options for a WhatsApp message.\n\n        **Relationship Context:** ${relationshipContext}\n\n        ${replyGoal ? `**My Explicit Goal for this Reply:** "${replyGoal}"` : ''}\n\n        **Message I am Replying To:**\n        """\n        ${messageToReplyTo}\n        """\n\n        ${messageHistory ? `**Additional Chat History for Context:**\n"""\n${messageHistory}\n"""` : ''}\n\n        **Relevant Past Interactions/Notes from My Memory (Use these for style and context):**\n        ${
      relevantMemories.length > 0
        ? relevantMemories.map((m) => `- "${m}"`).join('\n')
        : 'No specific memories retrieved.'
    }\n\n        ${additionalInstructions ? `**My Specific Instructions for This Draft:** ${additionalInstructions}` : ''}\n\n        **Your Output:**\n        Output a JSON array of objects, each with these fields:\n        - text: the draft reply (string)\n        - explanation: a one-sentence explanation of the strategy/tone for this draft (string)\n        - rank: integer, 1 for the top pick (most effective), 2 for the next, etc. (rank all drafts, do not tie)\n\n        Example:\n        [\n          { "text": "Hey! Thanks for reaching out...", "explanation": "Direct and friendly, sets a clear boundary.", "rank": 1 },\n          { "text": "Hi, appreciate your message...", "explanation": "Gentle and seeks to understand their perspective.", "rank": 2 }\n        ]\n\n        Do not add any extra explanations, apologies, or introductions. Only output the JSON array.\n        `;

    // --- Workflow Step 3: Call LLM ---
    const llmStartTime = Date.now();
    logger.info('[API /draft-whatsapp-reply] Calling LLM service...');
    const llmContent = await generateLLMResponse('DRAFT_COMMUNICATION', userObjectivePrompt, {
      systemContext: systemPrompt,
      temperature: 0.85,
      maxTokens: 1500,
    });
    const llmDuration = Date.now() - llmStartTime;
    logger.info(`[API /draft-whatsapp-reply] LLM call completed in ${llmDuration}ms.`);

    // --- Workflow Step 4: Parse & Respond ---
    let drafts: { text: string; explanation: string; rank: number }[] = [];
    try {
      if (!llmContent.success) {
        throw new Error(llmContent.error || 'LLM call failed to return successful content.');
      }
      // Try to parse the LLM's JSON output
      drafts = JSON.parse(llmContent.content);
      // Sort by rank ascending (1 = top pick)
      drafts.sort((a, b) => a.rank - b.rank);
    } catch (parseErr: unknown) {
      logger.error('[API /draft-whatsapp-reply] Failed to parse LLM JSON output.', {
        parseError: parseErr instanceof Error ? parseErr.message : String(parseErr),
        rawLLMContent: llmContent,
        stack: parseErr instanceof Error ? parseErr.stack : 'No stack trace available',
      });
      return NextResponse.json(
        {
          success: false,
          error: 'Failed to parse LLM output as JSON.',
          raw: llmContent,
        },
        { status: 500 }
      );
    }
    const duration = Date.now() - startTime;
    logger.info(`[API /draft-whatsapp-reply] Request completed successfully in ${duration}ms.`);
    return NextResponse.json({ success: true, drafts, relevantMemories });
  } catch (error: unknown) {
    const duration = Date.now() - startTime;
    logger.error(`[API /draft-whatsapp-reply] An unexpected error occurred after ${duration}ms:`, {
      error: error instanceof Error ? error.message : String(error),
      stack: error instanceof Error ? error.stack : 'No stack trace available',
    });
    return NextResponse.json(
      {
        success: false,
        error: 'An unexpected error occurred.',
        details: error instanceof Error ? error.message : 'Unknown error',
      },
      { status: 500 }
    );
  }
}
