/**
 * @fileoverview Main UI page for the Narrative Clarity Studio in the Orion admin dashboard.
 * @description This page serves as a central hub for self-reflection, personal narrative generation,
 *   career milestone management, sequential thinking, and now, personalized words of affirmation.
 *   It aims to provide a comprehensive suite of tools for personal and professional growth, leveraging
 *   AI to enhance insight and productivity.
 *
 * GOAL OF FILE|FEATURES|FUNCTIONS:
 *   - Provide a user interface for generating personal narratives using LLMs.
 *   - Manage and visualize career milestones to track professional growth.
 *   - Facilitate sequential thinking for breaking down complex problems.
 *   - Display LLM service health for monitoring API key configurations.
 *   - Integrate a personalized words of affirmation generator based on user history.
 *
 * FILEPATH: `app/(orion_admin)/admin/narrative-clarity-studio/page.tsx`.
 *
 * CONNECTION/RELATION TO OTHER FILES|FEATURES|FUNCTIONS|FILEPATHS:
 *   - `@/lib/llm_providers.ts`: Used for `checkAllLlmApiKeys` to monitor LLM service health.
 *   - `@/lib/orion_llm.ts`: Imports `callSequentialThinking` for iterative LLM prompting and other LLM interactions.
 *   - `@/lib/types.ts`: Defines shared types like `CareerMilestone` and `LLMAPIKeyStatus`.
 *   - `@/components/ui/`: Utilizes various Shadcn UI components (Tabs, Button, Textarea, Label, Card) for consistent styling.
 *   - `lucide-react`: Imports various icons (`Loader2`, `PlusCircle`, `AlertTriangle`, `Info`, `CheckCircle`, `XCircle`, `Sparkles`).
 *   - `@/components/orion/narrative-clarity-studio/CareerMilestoneProvider.tsx`: Provides context for managing career milestones.
 *   - `@/components/orion/narrative-clarity-studio/NarrativeGenerationForm.tsx`: Component for the main narrative generation input.
 *   - `@/components/orion/narrative-clarity-studio/CareerMilestoneList.tsx`: Component for displaying and managing career milestones.
 *   - `@/components/orion/narrative-clarity-studio/CareerMilestoneForm.tsx`: Component for adding/editing career milestones.
 *   - `@/components/orion/narrative-clarity-studio/AffirmationsGenerator.tsx`: (Newly integrated) Component for generating and displaying affirmations.
 *   - `app/api/orion/llm/health/route.ts`: API endpoint for checking LLM health.
 *   - `app/api/orion/llm/generate-circular-flow/route.ts`: API endpoint for generating narrative flow data.
 *   - `app/api/orion/llm/route.ts`: General LLM API endpoint for improvements.
 *
 * ASSUMPTIONS & CLEAR COMMENTS:
 *   - Assumes LLM API keys are correctly configured in the environment for full functionality.
 *   - Relies on backend APIs for LLM interactions and data persistence (e.g., career milestones).
 *   - The ReactFlow (D3.js visualization) sections are currently placeholders for future implementation.
 *
 * NOTES:
 *   - **COMPONENTS TO MERGE WITH / OPPORTUNITIES TO CONSOLIDATE:**
 *     - Consider consolidating sequential thinking and narrative generation forms if their core input/output patterns become very similar.
 *   - **PERFORMANCE OPTIMIZATIONS:**
 *     - Optimize LLM calls: Implement caching for frequently requested LLM responses where appropriate.
 *     - Lazy load tabs: For performance, consider dynamic imports for components within less frequently used tabs.
 *   - **ERROR HANDLING ROBUSTNESS:**
 *     - Enhance error messages: Provide more specific and actionable feedback to the user based on API error responses.
 *     - Implement retry mechanisms: For transient network or API errors in client-side fetches.
 *
 * OPPORTUNITIES FOR IMPROVEMENT & COMPREHENSIVE NEXT STEPS:
 *   The "Narrative Clarity Studio" is destined to be your ultimate central hub for self-reflection, goal setting,
 *   and continuous personal and professional growth, deeply integrated with every aspect of your digital life.
 *   The "Words of Affirmation" feature is a powerful and immediate step towards this vision, directly providing
 *   personalized positive reinforcement.
 *
 *   **1. Full Narrative Visualization & Interactive Flow (`D3.js` Integration):**
 *     - **Goal:** Bring the "Opportunity Pipeline Flow" and "Narrative Generation" visualizations to life!
 *       This involves transforming the conceptual flow into interactive, dynamic charts using `D3.js` or a similar library (like React Flow).
 *     - **How to Implement:**
 *       - **Frontend Components (`app/components/orion/narrative-clarity-studio/`):** Develop dedicated D3.js or React Flow components to render the "circular flow" generated by the backend and to visualize your career milestones as a journey.
 *         This will involve moving from commented-out placeholders to fully functional, interactive graphs.
 *       - **Data Transformation Utilities (`app/lib/utils/`):** Create utility functions to convert the raw data from `app/api/orion/llm/generate-circular-flow/route.ts` and your `CareerMilestone` data into the specific node and edge formats required by your chosen visualization library.
 *     - **Relevant Files:**
 *       - `app/(orion_admin)/admin/narrative-clarity-studio/page.tsx` (for rendering the main visualization component).
 *       - `app/api/orion/llm/generate-circular-flow/route.ts` (the backend API for narrative flow data).
 *       - New visualization-specific components (e.g., `app/components/orion/narrative-clarity-studio/NarrativeFlowVisualizer.tsx`).
 *       - Potentially new D3.js or graph-related utility functions in `app/lib/utils/`.
 *
 *   **2. Deeper & Interactive Sequential Thinking:**
 *     - **Goal:** Evolve the "Sequential Thinking" tab into an incredibly powerful, interactive tool that guides you through breaking down complex problems, projects, or goals into actionable, AI-supported steps.
 *     - **How to Implement:**
 *       - **Enhanced UI:** Develop a more dynamic UI that allows you to easily edit, reorder, and add new steps within a sequence. Consider visual progress indicators or "completion" states for each thought.
 *       - **AI Feedback Loop:** Implement a mechanism where the LLM can provide real-time feedback on your current step, suggest alternative approaches, or ask clarifying questions to refine your thinking process.
 *       - **Persistence & Collaboration:** Add functionality to save, load, and potentially share entire sequential thinking sessions (persisting them in Notion or Qdrant).
 *     - **Relevant Files:**
 *       - `app/(orion_admin)/admin/narrative-clarity-studio/page.tsx` (for the sequential thinking tab's logic and rendering).
 *       - `app/api/orion/llm/sequential-thinking/route.ts` (the backend API for sequential thought generation).
 *       - New dedicated components for managing and displaying interactive sequential steps.
 *
 *   **3. Comprehensive Career Milestone Management & AI Analysis:**
 *     - **Goal:** Expand the "Career Milestones" section to capture richer data, enable detailed progress tracking, and provide AI-driven insights into your career progression and skill development.
 *     - **How to Implement:**
 *       - **Enriched Data Fields:** Add more granular fields to each milestone, such as "quantifiable results," "lessons learned," "challenges faced," "key takeaways," and associated "skills developed."
 *       - **Progress Tracking:** Allow users to mark milestones as "planned," "in progress," "completed," or "on hold," with corresponding visual cues.
 *       - **AI Career Insights:** Develop an AI analysis feature that can examine your documented milestones, identify patterns, suggest potential career paths, highlight skill gaps, or recommend areas for further growth based on industry trends or your past achievements.
 *     - **Relevant Files:**
 *       - `app/lib/types/cv.ts` (for expanding the `CareerMilestone` type definition).
 *       - `app/components/orion/narrative-clarity-studio/CareerMilestoneForm.tsx` (for incorporating additional input fields).
 *       - `app/api/orion/cv-components/route.ts` (or a new dedicated API for career milestone management).
 *       - `app/lib/database.ts` (for handling updated database interactions).
 */

'use client';
import React, { useState, useEffect } from 'react';
// import { checkAllLlmApiKeys } from '@/lib/llm_providers'; // Removed unused import
import { callSequentialThinking } from '@/lib/orion_llm';
import { CareerMilestone } from '@/lib/types';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@radix-ui/react-tabs';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Card, CardHeader, CardTitle, CardContent } from '@/components/ui/card';
import { Loader2, PlusCircle, AlertTriangle, Info, CheckCircle, XCircle, Sparkles } from 'lucide-react';
import { CareerMilestoneProvider } from '@/components/orion/narrative-clarity-studio/CareerMilestoneProvider';
import { NarrativeGenerationForm } from '@/components/orion/narrative-clarity-studio/NarrativeGenerationForm';
import { CareerMilestoneList } from '@/components/orion/narrative-clarity-studio/CareerMilestoneList';
import { CareerMilestoneForm } from '@/components/orion/narrative-clarity-studio/CareerMilestoneForm';
import { AffirmationsGenerator } from '@/components/orion/narrative-clarity-studio/AffirmationsGenerator';

interface LLMAPIKeyStatus {
  modelId: string;
  present: boolean;
  reason?: string;
}

// Removed: These were initial values for ReactFlow nodes/edges, which are currently commented out.
// const initialNodes: Node[] = [];
// const initialEdges: Edge[] = [];

// Removed: This variable was assigned a value but never used.
// const pipelineStages = [
//   'Identified',
//   'Researching',
//   'Evaluating',
//   ''CV Tailoring'',
//   'Application Drafting',
//   'Outreach',
//   'Interview',
//   'Offer/Decision',
// ];

export default function NarrativeClarityStudio() {
  // Removed: ReactFlow related state variables as the tab is a placeholder.
  // const [nodes, setNodes] = useState<Node[]>(initialNodes);
  // const [edges, setEdges] = useState<Edge[]>(initialEdges);
  const [description, setDescription] = useState('');
  const [loading, setLoading] = useState(false);

  // LLM Health Check State
  const [llmHealth, setLlmHealth] = useState<LLMAPIKeyStatus[]>([]);
  const [llmHealthLoading, setLlmHealthLoading] = useState(true);
  const [llmHealthError, setLlmHealthError] = useState<string | null>(null);

  // Sequential Thinking State
  const [sequentialSteps, setSequentialSteps] = useState<string[]>([]);
  const [sequentialLoading, setSequentialLoading] = useState(false);
  const [sequentialError, setSequentialError] = useState<string | null>(null);
  const [sequentialThoughtNumber, setSequentialThoughtNumber] = useState(1);
  const [sequentialLastThought, setSequentialLastThought] = useState('');

  // Removed unused state: llmApiKeys was only used in commented-out/removed multiLLM logic.
  // const [llmApiKeys, setLlmApiKeys] = useState<LLMAPIKeyStatus[]>([]);

  const [sequentialWhy, setSequentialWhy] = useState<{ [idx: number]: string }>({});
  const [sequentialWhyLoading, setSequentialWhyLoading] = useState<{ [idx: number]: boolean }>({});

  // Career Milestones state
  const [milestones, setMilestones] = useState<CareerMilestone[]>([]);
  const [isLoadingMilestones, setIsLoadingMilestones] = useState<boolean>(true);
  const [milestonesError, setMilestonesError] = useState<string | null>(null);
  const [showAddMilestoneForm, setShowAddMilestoneForm] = useState<boolean>(false);
  const [editingMilestone, setEditingMilestone] = useState<CareerMilestone | null>(null);

  useEffect(() => {
    async function fetchHealth() {
      setLlmHealthLoading(true);
      setLlmHealthError(null);
      try {
        const res = await fetch('/api/orion/llm/health');
        const data = await res.json();
        if (data.success) {
          setLlmHealth(data.results);
        } else {
          setLlmHealthError('Failed to fetch LLM health');
        }
      } catch (err: unknown) {
        setLlmHealthError(err instanceof Error ? err.message : 'Unknown error');
      } finally {
        setLlmHealthLoading(false);
      }
    }
    fetchHealth();
  }, []);

  // Removed unused useEffect that was causing linter errors related to setLlmApiKeys.
  // useEffect(() => {
  //   setLlmApiKeys(checkAllLlmApiKeys());
  // }, []);

  // Commented out as ReactFlow is currently a placeholder and these functions are unused.
  // const onConnect = useCallback((params: Edge | Connection) => setEdges((eds: Edge[]) => addEdge(params, eds)), []);

  // Removed unused function: parseMarkdownToSteps was only used in commented-out/removed markdown logic.
  // const parseMarkdownToSteps = (md: string) => {
  //   return md
  //     .split(/\n|\r/)
  //     .map((s) => s.replace(/^\d+\.|^- /, '').trim())
  //     .filter(Boolean);
  // };

  const handleSequentialThinking = async (input: string, thoughtNumber = 1) => {
    setSequentialLoading(true);
    setSequentialError(null);
    try {
      const result = await callSequentialThinking({
        thought: input,
        nextThoughtNeeded: true,
        thoughtNumber,
        totalThoughts: 5,
      });
      if (result && typeof result === 'object' && 'thought' in result) {
        setSequentialLastThought(result.thought);
        setSequentialThoughtNumber(thoughtNumber);
        setSequentialSteps((prev) => [...prev.slice(0, thoughtNumber - 1), result.thought]);
      } else {
        setSequentialError('Sequential thinking tool did not return a valid thought.');
      }
    } catch (err: unknown) {
      setSequentialError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setSequentialLoading(false);
    }
  };

  const handleLLMGenerate = async () => {
    setLoading(true);
    setSequentialSteps([]);
    setSequentialThoughtNumber(1);
    await handleSequentialThinking(description, 1);
    setLoading(false);
  };

  const handleSequentialContinue = async () => {
    setSequentialLoading(true);
    setSequentialError(null);
    try {
      if (!sequentialLastThought) {
        throw new Error('No last thought to continue from.');
      }
      await handleSequentialThinking(sequentialLastThought, sequentialThoughtNumber + 1);
    } catch (err: unknown) {
      setSequentialError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setSequentialLoading(false);
    }
  };

  const handleSequentialWhy = async (idx: number, step: string) => {
    setSequentialWhyLoading((prev) => ({ ...prev, [idx]: true }));
    try {
      const res = await fetch('/api/orion/llm', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          requestType: 'NARRATIVE_EXPLANATION',
          primaryContext: sequentialSteps.join('\n'), // Context from all sequential thoughts
          secondaryContext: step,
          temperature: 0.5,
          maxTokens: 500,
        }),
      });
      const data = await res.json();
      if (data.success && data.content) {
        setSequentialWhy((prev) => ({ ...prev, [idx]: data.content }));
      } else {
        setSequentialWhy((prev) => ({ ...prev, [idx]: data.error || 'Failed to get explanation.' }));
      }
    } catch (err: unknown) {
      setSequentialWhy((prev) => ({ ...prev, [idx]: err instanceof Error ? err.message : 'Unknown error' }));
    } finally {
      setSequentialWhyLoading((prev) => ({ ...prev, [idx]: false }));
    }
  };

  const fetchCareerMilestones = async () => {
    setIsLoadingMilestones(true);
    setMilestonesError(null);
    try {
      const response = await fetch('/api/orion/career-milestones');
      const data = await response.json();
      if (data.success) {
        const sortedMilestones: CareerMilestone[] = data.milestones.sort(
          (a: CareerMilestone, b: CareerMilestone) => (a.order ?? 0) - (b.order ?? 0)
        );
        setMilestones(sortedMilestones);
        updateGraphWithMilestones(sortedMilestones); // Update graph when milestones change
      } else {
        setMilestonesError(data.error || 'Failed to fetch milestones');
      }
    } catch (err: unknown) {
      setMilestonesError(err instanceof Error ? err.message : 'Error fetching milestones');
      console.error('Error fetching milestones:', err);
    } finally {
      setIsLoadingMilestones(false);
    }
  };

  const handleMilestoneSubmit = async (data: Partial<CareerMilestone>) => {
    setLoading(true);
    setMilestonesError(null);
    try {
      const method = data.unique_id || data.notionPageId ? 'PUT' : 'POST';
      const url =
        data.unique_id || data.notionPageId
          ? `/api/orion/career-milestones/${data.unique_id || data.notionPageId}`
          : '/api/orion/career-milestones';

      const response = await fetch(url, {
        method,
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
      });

      const result = await response.json();

      if (response.ok && result.success) {
        fetchCareerMilestones();
        setShowAddMilestoneForm(false);
        setEditingMilestone(null);
      } else {
        throw new Error(result.error || 'Failed to save milestone');
      }
    } catch (err: unknown) {
      setMilestonesError(err instanceof Error ? err.message : 'Error saving milestone');
      console.error('Error saving milestone:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteMilestone = async (id: string) => {
    setLoading(true);
    setMilestonesError(null);
    try {
      const response = await fetch(`/api/orion/career-milestones/${id}`, {
        method: 'DELETE',
      });

      const result = await response.json();

      if (response.ok && result.success) {
        fetchCareerMilestones();
      } else {
        throw new Error(result.error || 'Failed to delete milestone');
      }
    } catch (err: unknown) {
      setMilestonesError(err instanceof Error ? err.message : 'Error deleting milestone');
      console.error('Error deleting milestone:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleReorderMilestone = async (id: string, direction: 'up' | 'down') => {
    setLoading(true);
    setMilestonesError(null);
    try {
      const updatedMilestones = milestones.map((m) => ({ ...m })); // Create a deep copy
      const index = updatedMilestones.findIndex((m) => m.notionPageId === id || m.unique_id === id);

      if (index === -1) throw new Error('Milestone not found');

      const currentOrder = updatedMilestones[index].order ?? 0;

      let targetIndex = -1;
      if (direction === 'up' && index > 0) {
        targetIndex = index - 1;
      } else if (direction === 'down' && index < updatedMilestones.length - 1) {
        targetIndex = index + 1;
      }

      if (targetIndex !== -1) {
        // Swap orders
        const targetOrder = updatedMilestones[targetIndex].order ?? 0;
        updatedMilestones[index].order = targetOrder;
        updatedMilestones[targetIndex].order = currentOrder;

        // Sort and update Notion (simplified for example, full reordering might involve more complex logic)
        const reorderedForNotion = updatedMilestones.sort((a, b) => (a.order ?? 0) - (b.order ?? 0));

        const response = await fetch('/api/orion/career-milestones/reorder', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            milestones: reorderedForNotion.map((m) => ({ id: m.notionPageId || m.unique_id, order: m.order })),
          }),
        });

        const result = await response.json();

        if (response.ok && result.success) {
          fetchCareerMilestones();
        } else {
          throw new Error(result.error || 'Failed to reorder milestone');
        }
      }
    } catch (err: unknown) {
      setMilestonesError(err instanceof Error ? err.message : 'Error reordering milestone');
      console.error('Error reordering milestone:', err);
    } finally {
      setLoading(false);
    }
  };

  const updateGraphWithMilestones = (updatedMilestones: CareerMilestone[]) => {
    updatedMilestones.map((milestone) => ({
      id: (milestone.notionPageId || milestone.unique_id || `temp-id-${Math.random()}`).toString(), // Use notionPageId, unique_id, or a generated temp ID as a string
      data: { label: milestone.title },
      position: { x: Math.random() * 500, y: Math.random() * 500 }, // Placeholder for positioning
      // Add other relevant milestone data here
    }));

    // You might add logic here to create edges based on relationships between milestones if defined

    // Commented out as ReactFlow is currently a placeholder.
    // setNodes((prevNodes) => {
    //   // Merge existing nodes with new nodes, preferring new nodes if IDs conflict
    //   const mergedNodesMap = new Map<string, Node>();
    //   prevNodes.forEach((node) => mergedNodesMap.set(node.id, node));
    //   newNodes.forEach((node) => mergedNodesMap.set(node.id, node));
    //   return Array.from(mergedNodesMap.values()).sort((a, b) => (a.data.order ?? 0) - (b.data.order ?? 0));
    // });
    // setEdges((prevEdges) => [...prevEdges, ...newEdges]);
  };

  return (
    <div className="container mx-auto py-8 space-y-8">
      <h1 className="text-3xl font-bold mb-6">Narrative Clarity Studio</h1>

      {/* Affirmations Section - Added here */}
      <section className="space-y-6">
        <h2 className="text-2xl font-semibold">Words of Affirmation</h2>
        <AffirmationsGenerator />
      </section>

      <Tabs defaultValue="narrative-generation" className="w-full">
        <TabsList className="grid w-full grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
          <TabsTrigger value="narrative-generation">Narrative Generation</TabsTrigger>
          <TabsTrigger value="career-milestones">Career Milestones</TabsTrigger>
          <TabsTrigger value="sequential-thinking">Sequential Thinking</TabsTrigger>
          <TabsTrigger value="llm-health">LLM Health Check</TabsTrigger>
        </TabsList>

        <TabsContent value="narrative-generation">
          <Card className="bg-gray-800 border-gray-700">
            <CardHeader>
              <CardTitle className="text-xl font-semibold text-blue-300 flex items-center">
                <Sparkles className="mr-2 h-5 w-5" /> Narrative Generation
              </CardTitle>
              <CardContent className="space-y-4">
                <NarrativeGenerationForm
                  description={description}
                  setDescription={setDescription}
                  handleLLMGenerate={handleLLMGenerate}
                  loading={loading}
                  llmError={sequentialError}
                />
              </CardContent>
            </CardHeader>
          </Card>
        </TabsContent>

        <TabsContent value="career-milestones">
          <CareerMilestoneProvider
            submitMilestone={handleMilestoneSubmit}
            deleteMilestone={handleDeleteMilestone}
            reorderMilestone={handleReorderMilestone}
          >
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">
              <Card>
                <CardHeader>
                  <CardTitle>Manage Career Milestones</CardTitle>
                </CardHeader>
                <CardContent>
                  {isLoadingMilestones ? (
                    <div className="flex items-center justify-center py-8">
                      <Loader2 className="h-8 w-8 animate-spin text-primary" />
                      <span className="ml-2 text-primary">Loading Milestones...</span>
                    </div>
                  ) : milestonesError ? (
                    <div className="text-red-500 flex items-center justify-center">
                      <AlertTriangle className="mr-2" />
                      Error: {milestonesError}
                    </div>
                  ) : (
                    <CareerMilestoneList
                      milestones={milestones}
                      isLoading={isLoadingMilestones}
                      error={milestonesError}
                      onEdit={setEditingMilestone}
                      onDelete={handleDeleteMilestone}
                      onReorder={handleReorderMilestone}
                    />
                  )}
                  <Button onClick={() => setShowAddMilestoneForm(true)} className="mt-4 w-full">
                    <PlusCircle className="mr-2 h-4 w-4" /> Add New Milestone
                  </Button>
                </CardContent>
              </Card>
              <Card>
                <CardHeader>
                  <CardTitle>{editingMilestone ? 'Edit Milestone' : 'Add New Milestone'}</CardTitle>
                </CardHeader>
                <CardContent>
                  {showAddMilestoneForm || editingMilestone ? (
                    <CareerMilestoneForm
                      onSubmit={handleMilestoneSubmit}
                      onCancel={() => {
                        setShowAddMilestoneForm(false);
                        setEditingMilestone(null);
                      }}
                      initialData={editingMilestone || undefined}
                      existingMilestonesCount={milestones.length}
                    />
                  ) : (
                    <p className="text-center text-gray-500 dark:text-gray-400 py-8">
                      Click &quot;Add New Milestone&quot; to begin building your career narrative.
                    </p>
                  )}
                </CardContent>
              </Card>
            </div>
          </CareerMilestoneProvider>
        </TabsContent>

        <TabsContent value="sequential-thinking">
          <Card className="mt-4">
            <CardHeader>
              <CardTitle>Sequential Thinking (Iterative LLM Prompting)</CardTitle>
            </CardHeader>
            <CardContent className="pt-4">
              <div className="space-y-4">
                <div>
                  <Label htmlFor="sequential-input">Initial Thought / Prompt</Label>
                  <Textarea
                    id="sequential-input"
                    value={description}
                    onChange={(e) => setDescription(e.target.value)}
                    placeholder="Start your sequential thought process..."
                    rows={3}
                  />
                </div>
                <Button
                  onClick={() => handleSequentialThinking(description)}
                  disabled={sequentialLoading || !description}
                >
                  {sequentialLoading ? (
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  ) : (
                    <Sparkles className="mr-2 h-4 w-4" />
                  )}{' '}
                  Start Sequential Thinking
                </Button>

                {sequentialError && (
                  <div className="text-red-500 flex items-center">
                    <AlertTriangle className="mr-2" /> Error: {sequentialError}
                  </div>
                )}

                {sequentialSteps.length > 0 && (
                  <div className="space-y-2 mt-4">
                    <h3 className="text-lg font-semibold">Thought Process:</h3>
                    {sequentialSteps.map((step, idx) => (
                      <div key={idx} className="border p-3 rounded-md bg-gray-50 dark:bg-gray-800">
                        <div className="flex justify-between items-center">
                          <p className="font-medium">
                            Step {idx + 1}: <span className="italic">{step}</span>
                          </p>
                          <Button
                            variant="ghost"
                            size="sm"
                            onClick={() => handleSequentialWhy(idx, step)}
                            disabled={sequentialWhyLoading[idx]}
                          >
                            {sequentialWhyLoading[idx] ? (
                              <Loader2 className="h-4 w-4 animate-spin" />
                            ) : (
                              <Info className="h-4 w-4" />
                            )}{' '}
                            Why?
                          </Button>
                        </div>
                        {sequentialWhy[idx] && (
                          <p className="text-sm text-gray-600 dark:text-gray-400 mt-1 italic">
                            <span className="font-semibold">Reasoning:</span> {sequentialWhy[idx]}
                          </p>
                        )}
                      </div>
                    ))}
                  </div>
                )}

                {sequentialLastThought && !sequentialLoading && (
                  <div className="mt-4">
                    <Label htmlFor="next-thought">Next Thought</Label>
                    <Textarea
                      id="next-thought"
                      value={sequentialLastThought}
                      onChange={(e) => setSequentialLastThought(e.target.value)}
                      placeholder="Refine or continue the thought..."
                      rows={3}
                    />
                    <Button
                      onClick={() => handleSequentialContinue()}
                      disabled={sequentialLoading || !sequentialLastThought}
                      className="mt-2"
                    >
                      {sequentialLoading ? (
                        <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                      ) : (
                        <Sparkles className="mr-2 h-4 w-4" />
                      )}{' '}
                      Continue Sequential Thinking
                    </Button>
                  </div>
                )}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="llm-health">
          <Card className="mt-4">
            <CardHeader>
              <CardTitle>LLM Service Health Check</CardTitle>
              <CardContent className="pt-4">
                {llmHealthLoading ? (
                  <div className="flex items-center justify-center py-8">
                    <Loader2 className="h-8 w-8 animate-spin text-primary" />
                    <span className="ml-2 text-primary">Checking LLM Services...</span>
                  </div>
                ) : llmHealthError ? (
                  <div className="text-red-500 flex items-center justify-center">
                    <AlertTriangle className="mr-2" />
                    Error: {llmHealthError}
                  </div>
                ) : (
                  <div className="space-y-4">
                    {llmHealth.map((status) => (
                      <div key={status.modelId} className="flex items-center space-x-3">
                        {status.present ? (
                          <CheckCircle className="h-5 w-5 text-green-500" />
                        ) : (
                          <XCircle className="h-5 w-5 text-red-500" />
                        )}
                        <span className="font-medium">{status.modelId}:</span>
                        <span className={status.present ? 'text-green-600' : 'text-red-600'}>
                          {status.present ? 'Active' : `Inactive (${status.reason || 'Unknown reason'})`}
                        </span>
                      </div>
                    ))}
                    <p className="text-sm text-gray-500 mt-4">
                      Ensure all required LLM API keys are set in your environment variables.
                    </p>
                  </div>
                )}
              </CardContent>
            </CardHeader>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Placeholder for future D3.js visualization. */}
      {/* {nodes.length > 0 && ( */}
      {/* <div className="mt-8 h-[500px]"> */}
      {/* <ReactFlow */}
      {/* nodes={nodes} */}
      {/* edges={edges} */}
      {/* onNodesChange={onNodesChange} */}
      {/* onEdgesChange={onEdgesChange} */}
      {/* onConnect={onConnect} */}
      {/* fitView */}
      {/* > */}
      {/* <Controls /> */}
      {/* <MiniMap /> */}
      {/* <Background variant="dots" gap={12} size={1} /> */}
      {/* </ReactFlow> */}
      {/* </div> */}
      {/* )} */}
    </div>
  );
}
